/** Type stub for the WASM module generated by wasm-pack. */
declare module '*pkg/requencer_web' {
  export default function init(): Promise<void>
  export class WasmSequencer {
    // Transport
    set_bpm(bpm: number): void
    set_playing(playing: boolean): void

    // UI navigation
    set_screen(screen: number): void
    set_selected_track(track: number): void
    set_selected_step(step: number): void
    set_current_page(page: number): void
    set_rand_param(param: number): void
    set_route_param(param: number): void
    set_mutate_param(param: number): void
    set_xpose_param(param: number): void
    set_settings_scroll(scroll: number): void
    set_mod_lfo_view(view: boolean): void

    // Variation UI
    set_var_selected_bar(bar: number): void
    set_var_cursor(cursor: number): void

    // Name entry
    set_name_char(index: number, char: number): void
    set_name_cursor(cursor: number): void
    set_name_len(len: number): void
    set_name_context(isPattern: boolean): void

    // Flash message
    set_flash_message(msg: string): void

    // Playheads & subtracks
    set_playhead(track: number, subtrack: number, step: number): void
    set_subtrack_length(track: number, subtrack: number, len: number): void
    set_subtrack_divider(track: number, subtrack: number, div: number): void
    set_track_divider(track: number, div: number): void

    // Gate steps
    toggle_gate(track: number, step: number): void
    set_gate_on(track: number, step: number, on: boolean): void
    set_gate_tie(track: number, step: number, tie: boolean): void
    set_gate_length(track: number, step: number, length: number): void
    set_ratchet(track: number, step: number, ratchet: number): void

    // Pitch steps
    set_pitch_note(track: number, step: number, note: number): void
    set_slide(track: number, step: number, slide: number): void

    // Velocity & mod steps
    set_velocity(track: number, step: number, vel: number): void
    set_mod_value(track: number, step: number, value: number): void
    set_mod_slew(track: number, step: number, slew: number): void

    // Mute steps
    set_mute_length(track: number, len: number): void
    set_mute_divider(track: number, div: number): void
    set_mute_step(track: number, step: number, muted: boolean): void

    // Routing
    set_route_gate(output: number, gate: number): void
    set_route_pitch(output: number, pitch: number): void
    set_route_velocity(output: number, velocity: number): void
    set_route_mod(output: number, mod: number): void
    set_mod_source(output: number, source: number): void

    // LFO
    set_lfo_waveform(track: number, waveform: number): void
    set_lfo_sync_mode(track: number, mode: number): void
    set_lfo_rate(track: number, rate: number): void
    set_lfo_free_rate(track: number, rate: number): void
    set_lfo_depth(track: number, depth: number): void
    set_lfo_offset(track: number, offset: number): void
    set_lfo_width(track: number, width: number): void
    set_lfo_phase(track: number, phase: number): void

    // Transpose
    set_transpose_semitones(track: number, semitones: number): void
    set_transpose_range(track: number, low: number, high: number): void
    set_transpose_gl_scale(track: number, scale: number): void
    set_transpose_vel_scale(track: number, scale: number): void

    // Mutate
    set_mutate_trigger(track: number, trigger: number): void
    set_mutate_bars(track: number, bars: number): void
    set_mutate_rates(track: number, gate: number, pitch: number, velocity: number, modulation: number): void

    // Variation
    set_variation_enabled(track: number, enabled: boolean): void
    set_variation_length(track: number, length: number): void
    set_variation_loop(track: number, loop: boolean): void

    // Rendering
    render_in_place(): void
    render(): Uint8Array
    width(): number
    height(): number
    buffer_ptr(): number
    buffer_len(): number

    // Engine tick
    tick(): Float32Array
  }
}
