#!/usr/bin/env python3
"""Place components on KiCad PCB using positions from panel-layout.json.

Reads the .kicad_pcb generated by `ato build`, places through-hole components
at their faceplate positions, and groups SMD components near their connected
through-hole counterparts.

Components are looked up by their atopile_address property (not reference
designator), since atopile auto-assigns generic refs like R1, C1, etc.

Supports multi-board builds:
  - Control board (default): Full panel placement with layout + zones.
  - Main board (--board main): Compact grid placement, no panel layout.
    Detected via --board flag or "main" in PCB filename.

Usage:
    python place_components.py [--board control|main] <input.kicad_pcb> [output.kicad_pcb]

Requires: KiCad's pcbnew Python module (available in KiCad installation or Docker).
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict

LAYOUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "web", "src", "panel-layout.json")
COMPONENT_MAP_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "component-map.json")
BOARD_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "board-config.json")


def load_board_config():
    with open(BOARD_CONFIG_PATH) as f:
        return json.load(f)


def load_layout():
    with open(LAYOUT_PATH) as f:
        return json.load(f)


def load_component_map():
    with open(COMPONENT_MAP_PATH) as f:
        return json.load(f)


def identify_power_nets(board):
    """Return set of net names that are power/ground (useless for placement affinity).

    Uses two heuristics:
      1. Name patterns: gnd, vcc, vdd, 3v3, 5v, 12v, avdd, etc.
      2. High fanout: any net connected to >15 pads is likely power.
    """
    power_pattern = re.compile(
        r"(^|\W)(gnd|vcc|vdd|vss|avdd|avss|dvdd|dvss"
        r"|v5v|v3v3|v12p|v12n|\+12v|\-12v|\+5v|\+3\.3v"
        r"|hv|vsys|vbus|vref|agnd|dgnd|pgnd)"
        r"($|\W)",
        re.IGNORECASE,
    )
    power_nets = set()

    # Pattern-based detection
    netinfo = board.GetNetInfo()
    for net in netinfo.NetsByName():
        name = str(net)
        if power_pattern.search(name):
            power_nets.add(name)

    # Fanout-based detection: count pads per net
    pad_count = defaultdict(int)
    for fp in board.GetFootprints():
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name:
                pad_count[net_name] += 1
    for net_name, count in pad_count.items():
        if count > 15:
            power_nets.add(net_name)

    return power_nets


def build_connectivity_graph(board, addrs, addr_map, power_nets):
    """Build adjacency graph: addr -> {neighbor_addr: shared_net_count}.

    Two SMD components are connected if they share at least one non-power net.
    """
    # Map net_name -> list of addrs that have pads on that net
    net_to_addrs = defaultdict(set)
    for addr in addrs:
        fp = addr_map[addr]
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name and net_name not in power_nets:
                net_to_addrs[net_name].add(addr)

    # Build adjacency from shared nets
    graph = defaultdict(lambda: defaultdict(int))
    for net_name, connected_addrs in net_to_addrs.items():
        addr_list = list(connected_addrs)
        for i in range(len(addr_list)):
            for j in range(i + 1, len(addr_list)):
                graph[addr_list[i]][addr_list[j]] += 1
                graph[addr_list[j]][addr_list[i]] += 1

    return graph


def connectivity_sort(addrs, graph):
    """Order components so electrically-connected ones are adjacent.

    Greedy BFS: start from the most-connected node, always visit the
    unvisited neighbor with the strongest connection. Handles disconnected
    subgraphs -- isolated components go at the end.
    """
    if not addrs:
        return []

    remaining = set(addrs)
    ordered = []

    while remaining:
        # Pick start node: most total connection weight among remaining
        start = max(
            remaining,
            key=lambda a: sum(graph[a].get(n, 0) for n in remaining) if a in graph else 0,
        )
        remaining.remove(start)
        ordered.append(start)

        # Greedy walk: always pick the strongest unvisited neighbor
        current = start
        while True:
            neighbors = {
                n: w for n, w in graph.get(current, {}).items() if n in remaining
            }
            if not neighbors:
                # No connected unvisited neighbors -- check if any remaining
                # node connects to ANY already-ordered node
                best = None
                best_w = 0
                for r in remaining:
                    for o in ordered:
                        w = graph.get(r, {}).get(o, 0)
                        if w > best_w:
                            best = r
                            best_w = w
                if best and best_w > 0:
                    remaining.remove(best)
                    ordered.append(best)
                    current = best
                    continue
                break
            best_neighbor = max(neighbors, key=neighbors.get)
            remaining.remove(best_neighbor)
            ordered.append(best_neighbor)
            current = best_neighbor

    return ordered


def size_sort(addrs, addr_map, pcbnew):
    """Sort component addresses by footprint bounding-box area, largest first."""
    def area(addr):
        fp = addr_map.get(addr)
        if not fp:
            return 0
        bbox = fp.GetBoundingBox(False, False)
        return pcbnew.ToMM(bbox.GetWidth()) * pcbnew.ToMM(bbox.GetHeight())
    return sorted(addrs, key=area, reverse=True)



def _get_padding_sequence(board_type):
    """Get padding sequence from board-config.json for iterative placement."""
    config = load_board_config()
    return config["boards"][board_type]["placement"]["padding_sequence"]


def place_main_board(input_pcb, output_pcb=None):
    """Place components on the main board with iterative padding.

    Tries placement with decreasing extra padding (4.0 → 0.0mm per side).
    Stops at the first padding level that produces zero overlaps, giving
    maximum spacing for label readability and routing channels.

    Always writes to a staging file. On success, promotes to output_pcb.
    On failure, keeps staging file for manual inspection in KiCad.
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python (see Makefile hw-place).")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    dir_name = os.path.dirname(output_pcb)
    fname = os.path.basename(output_pcb)
    staging_pcb = os.path.join(dir_name, fname.replace("-placed", "-staging-placed", 1))

    for padding in _get_padding_sequence("main"):
        n_overlaps = _place_main_board_pass(input_pcb, staging_pcb, padding, pcbnew)
        if n_overlaps == 0:
            print(f"  Padding: {padding:.1f}mm per side (0 overlaps)")
            os.rename(staging_pcb, output_pcb)
            print(f"  Promoted to {output_pcb}")
            return
        print(f"  Padding {padding:.1f}mm: {n_overlaps} overlaps — retrying with less")

    print(f"  FAIL: {n_overlaps} overlaps remain at 0mm padding")
    print(f"  Staging file for inspection: {staging_pcb}")
    sys.exit(1)


def _place_main_board_pass(input_pcb, output_pcb, extra_padding, pcbnew):
    """Single placement pass with given extra_padding. Returns overlap count."""
    from placement.helpers import (
        CollisionTracker, extract_footprint_dims, find_best_side,
        is_tht as is_tht_fn, regenerate_duplicate_uuids,
    )

    board = pcbnew.LoadBoard(input_pcb)

    # Enable 4 copper layers
    board.SetCopperLayerCount(4)

    # Build lookup from atopile_address to footprint
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp

    if not addr_map:
        print("  No components with atopile_address found.")
        board.Save(output_pcb)
        return

    # Classify components
    ic_pin_threshold = 5
    ics = []
    passives = []
    headers = []  # THT connectors

    for addr, fp in addr_map.items():
        pad_count = len(list(fp.Pads()))
        has_tht = any(
            pad.GetAttribute() == pcbnew.PAD_ATTRIB_PTH for pad in fp.Pads()
        )
        if has_tht:
            headers.append(addr)
        elif pad_count >= ic_pin_threshold:
            ics.append(addr)
        else:
            passives.append(addr)

    print(f"  Main board: {len(headers)} headers, {len(ics)} ICs, {len(passives)} passives")

    # Build connectivity graph for ordering
    power_nets = identify_power_nets(board)
    all_addrs = list(addr_map.keys())
    conn_graph = build_connectivity_graph(board, all_addrs, addr_map, power_nets)

    # Order by footprint area (largest first — big parts get first pick of positions)
    ics = size_sort(ics, addr_map, pcbnew)
    passives = size_sort(passives, addr_map, pcbnew)

    # Board dimensions and placement settings from config
    config = load_board_config()
    main_config = config["boards"]["main"]
    board_w = main_config["dimensions"]["width_mm"]
    board_h = main_config["dimensions"]["height_mm"]
    margin = main_config["placement"].get("margin", 3.0)
    smd_side = main_config["placement"].get("smd_side", "both")

    # Measure tallest header for zone sizing
    header_spacing = 18.0
    max_header_h = 0
    for addr in headers:
        fp = addr_map.get(addr)
        if fp:
            bbox = fp.GetBoundingBox(False, False)
            h = pcbnew.ToMM(bbox.GetHeight())
            max_header_h = max(max_header_h, h)
    header_zone_h = max(max_header_h + 4, 20.0)

    # Layout zones — smaller board, dual-side SMD placement
    ic_spacing = main_config["placement"].get("ic_spacing", 12.0)
    ic_cols = max(1, int((board_w - 2 * margin) / ic_spacing))
    ic_rows_count = (len(ics) + ic_cols - 1) // ic_cols if ics else 0
    ic_start_y = margin + header_zone_h + 5
    passive_spacing = main_config["placement"].get("passive_spacing", 5.0)
    passive_start_y = ic_start_y + ic_rows_count * ic_spacing + 5
    p_cols = max(1, int((board_w - 2 * margin) / passive_spacing))
    passive_rows = (len(passives) + p_cols - 1) // p_cols if passives else 0

    # Set board outline
    edge_layer = board.GetLayerID("Edge.Cuts")
    for x1, y1, x2, y2 in [
        (0, 0, board_w, 0), (board_w, 0, board_w, board_h),
        (board_w, board_h, 0, board_h), (0, board_h, 0, 0),
    ]:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Initialize collision tracker with extra padding for this pass
    tht_extra = main_config["placement"].get("tht_extra_clearance_mm", 0.0)
    tracker = CollisionTracker(board_w, board_h, clearance=0.5,
                               extra_padding=extra_padding,
                               tht_extra_clearance=tht_extra)
    placed = 0

    def place(addr, x, y, front=True):
        """Place component and register with collision tracker."""
        nonlocal placed
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        is_through = is_tht_fn(fp, pcbnew)
        # THT: body-only dims (text on headers is huge). SMD: include label.
        w, h, _, _ = extract_footprint_dims(fp, pcbnew)
        side = "F" if front else "B"
        tracker.register(x, y, w, h, side, is_through, label=addr)
        placed += 1

    def place_collision_free(addr, desired_x, desired_y, front, zone_bounds=None):
        """Place component at nearest collision-free position."""
        nonlocal placed
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        is_through = is_tht_fn(fp, pcbnew)
        w, h, _, _ = extract_footprint_dims(fp, pcbnew)
        side = "F" if front else "B"
        result = tracker.find_free(desired_x, desired_y, w, h, side, is_through,
                                   zone_bounds, step=0.5)
        if result is None:
            x, y = desired_x, desired_y  # fallback: place at desired position
        else:
            x, y = result
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        tracker.register(x, y, w, h, side, is_through, label=addr)
        placed += 1

    # Place THT components with explicit positions from config.
    named_pos = main_config["placement"].get("named_positions", {})
    tht_positions = {
        addr: (pos["x"], pos["y"], pos["front"])
        for addr, pos in named_pos.items()
    }
    for addr in headers:
        if addr in tht_positions:
            hx, hy, front = tht_positions[addr]
        else:
            # Fallback: spread evenly across board width
            idx = headers.index(addr)
            hx = margin + 20 + idx * (board_w - 2 * margin - 40) / max(len(headers) - 1, 1)
            hy = margin + header_zone_h / 2
            front = True
        place_collision_free(addr, hx, hy, front=front,
                             zone_bounds=(margin, margin, board_w - 2 * margin, header_zone_h))

    # USB-C — edge-mounted at left board edge, front side for single-side SMD assembly.
    # Mid-mount connector: body on board, mouth flush with edge.
    # At 90° rotation, connector Y- (mouth, 6.5mm) maps to board X+.
    usb_addr = "usb"
    if usb_addr in addr_map:
        fp = addr_map[usb_addr]
        usb_x = 5.0             # left edge — cable plugs in from side of module
        usb_y = board_h / 2 + 10  # below center (52mm), swapped with bootsel
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(usb_x), pcbnew.FromMM(usb_y)))
        # Ensure on front side
        if fp.GetLayer() != board.GetLayerID("F.Cu"):
            fp.Flip(fp.GetPosition(), False)
        fp.SetOrientationDegrees(90)  # rotate so mouth faces left (toward rack side)
        w, h, _, _ = extract_footprint_dims(fp, pcbnew)
        # Register as through-hole — mid-mount USB-C has shield tabs/holding
        # pins that poke through, so no SMDs on opposite side.
        tracker.register(usb_x, usb_y, w, h, "F", True, label=usb_addr)
        placed += 1
        # Remove from generic lists to prevent double placement
        if usb_addr in ics:
            ics.remove(usb_addr)
        if usb_addr in passives:
            passives.remove(usb_addr)

    # Bootsel button — front side near USB-C for single-side SMD assembly.
    # PTS645 has mechanical anchor pins that poke through, so treat as through-hole
    # for exclusion purposes (no SMDs on opposite side at this position).
    bootsel_addr = "mcu.sw_bootsel"
    if bootsel_addr in addr_map:
        fp = addr_map[bootsel_addr]
        bx = 5.0        # near USB-C on left edge
        by = board_h / 2  # vertically centered (42mm), swapped with USB-C
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(bx), pcbnew.FromMM(by)))
        # Ensure on front side
        if fp.GetLayer() != board.GetLayerID("F.Cu"):
            fp.Flip(fp.GetPosition(), False)
        w, h, _, _ = extract_footprint_dims(fp, pcbnew)
        # Register as through-hole to create exclusion on both sides
        tracker.register(bx, by, w, h, "F", True, label=bootsel_addr)
        placed += 1
        if bootsel_addr in ics:
            ics.remove(bootsel_addr)
        if bootsel_addr in passives:
            passives.remove(bootsel_addr)

    # --- Connectivity-aware SMD placement ---
    # For each IC and passive, compute the target position as the centroid
    # of its already-placed connected neighbors. Side restricted by
    # smd_side config ("F", "B", or "both").
    board_zone = (margin, margin, board_w - 2 * margin, board_h - 2 * margin)

    def connectivity_target(addr):
        """Compute target (x, y) as centroid of placed neighbors + repulsion.

        Attraction: centroid of electrically connected placed components.
        Repulsion: push away from nearby placed components to prevent clustering.
        """
        neighbors = conn_graph.get(addr, {})
        positions = []
        for n in neighbors:
            nfp = addr_map.get(n)
            if nfp and n in placed_addrs_set:
                npos = nfp.GetPosition()
                positions.append((pcbnew.ToMM(npos.x), pcbnew.ToMM(npos.y)))
        if positions:
            cx = sum(p[0] for p in positions) / len(positions)
            cy = sum(p[1] for p in positions) / len(positions)
        else:
            cx, cy = board_w / 2, board_h / 2

        # Apply repulsion from nearby placed components
        rx, ry = tracker.repulsion_offset(cx, cy)
        tx = max(margin, min(board_w - margin, cx + rx))
        ty = max(margin, min(board_h - margin, cy + ry))
        return (tx, ty)

    def place_nearest_side(addr):
        """Place component on the allowed SMD side(s) per config."""
        nonlocal placed
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        w, h, _, _ = extract_footprint_dims(fp, pcbnew)
        is_through = is_tht_fn(fp, pcbnew)
        tx, ty = connectivity_target(addr)

        result = find_best_side(tracker, tx, ty, w, h, is_through,
                                step=0.5, smd_side=smd_side)
        if result:
            x, y, side = result
        else:
            x, y, side = tx, ty, smd_side if smd_side != "both" else "F"

        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        target_front = side == "F"
        current_front = fp.GetLayer() == board.GetLayerID("F.Cu")
        if target_front != current_front:
            fp.Flip(fp.GetPosition(), False)
        tracker.register(x, y, w, h, side, is_through, label=addr)
        placed += 1
        placed_addrs_set.add(addr)

    placed_addrs_set = set()
    # Record already-placed THT components
    for addr in list(addr_map.keys()):
        if addr not in ics and addr not in passives:
            placed_addrs_set.add(addr)

    # Place ICs first (larger, get priority), then passives
    # Order by connectivity strength so well-connected parts place first
    ics = connectivity_sort(ics, conn_graph)
    passives = connectivity_sort(passives, conn_graph)

    for addr in ics:
        place_nearest_side(addr)

    for addr in passives:
        place_nearest_side(addr)

    # Check overlaps
    overlaps = tracker.overlap_report()
    n_overlaps = len(overlaps)
    if n_overlaps == 0:
        print(f"  Overlap check: PASS (0 collisions among {placed} components)")
    else:
        print(f"  Overlap check: {n_overlaps} overlaps")
    print(f"  Board dimensions: {board_w:.1f} x {board_h:.1f} mm")
    print(f"  Placed {placed}/{len(addr_map)} components")
    board.Save(output_pcb)
    n_fixed = regenerate_duplicate_uuids(output_pcb)
    if n_fixed:
        print(f"  Fixed {n_fixed} duplicate pad UUIDs")
    print(f"  Saved to {output_pcb}")
    return n_overlaps


def place_components(input_pcb, output_pcb=None):
    """Place components on control board with iterative padding.

    Tries placement with decreasing extra padding (2.0 → 0.0mm per side).
    Stops at the first padding level that produces zero overlaps.

    Always writes to a staging file. On success, promotes to output_pcb.
    On failure, keeps staging file for manual inspection in KiCad.
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python (see Makefile hw-place).")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    dir_name = os.path.dirname(output_pcb)
    fname = os.path.basename(output_pcb)
    staging_pcb = os.path.join(dir_name, fname.replace("-placed", "-staging-placed", 1))

    for padding in _get_padding_sequence("control"):
        n_overlaps = _place_control_board_pass(input_pcb, staging_pcb, padding, pcbnew)
        if n_overlaps == 0:
            print(f"  Padding: {padding:.1f}mm per side (0 overlaps)")
            os.rename(staging_pcb, output_pcb)
            print(f"  Promoted to {output_pcb}")
            return
        print(f"  Padding {padding:.1f}mm: {n_overlaps} overlaps — retrying with less")

    print(f"  FAIL: {n_overlaps} overlaps remain at 0mm padding")
    print(f"  Staging file for inspection: {staging_pcb}")
    sys.exit(1)


def _place_control_board_pass(input_pcb, output_pcb, extra_padding, pcbnew):
    """Single control board placement pass. Returns overlap count."""
    from placement.helpers import (
        CollisionTracker, extract_footprint_dims, is_tht as is_tht_fn,
        get_ref_text_bbox, regenerate_duplicate_uuids,
    )

    layout = load_layout()
    panel = layout["panel"]
    comp_map = load_component_map()
    pcb_dims = comp_map["pcb"]

    # PCB origin offset in faceplate coordinates
    # Faceplate coord (ox, oy) maps to PCB coord (0, 0)
    ox = pcb_dims["origin_x_mm"]
    oy = pcb_dims["origin_y_mm"]

    board = pcbnew.LoadBoard(input_pcb)

    # Enable 4 copper layers (F.Cu, In1.Cu, In2.Cu, B.Cu)
    # 2 layers is insufficient for 255 components / 319 nets at this density
    board.SetCopperLayerCount(4)

    # Set board outline (PCB is smaller than faceplate -- fits between rails)
    w_mm = pcb_dims["width_mm"]
    h_mm = pcb_dims["height_mm"]
    edge_layer = board.GetLayerID("Edge.Cuts")

    seg_coords = [
        (0, 0, w_mm, 0),
        (w_mm, 0, w_mm, h_mm),
        (w_mm, h_mm, 0, h_mm),
        (0, h_mm, 0, 0),
    ]
    for x1, y1, x2, y2 in seg_coords:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Build lookup from atopile_address to footprint
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp

    # Initialize collision tracker with extra padding for this pass
    ctrl_config = load_board_config()
    tht_extra = ctrl_config["boards"]["control"]["placement"].get(
        "tht_extra_clearance_mm", 0.0)
    tracker = CollisionTracker(w_mm, h_mm, clearance=0.5,
                               extra_padding=extra_padding,
                               tht_extra_clearance=tht_extra)

    placed = 0
    placed_addrs = set()
    warnings = []

    def place(addr, x_mm, y_mm, front=True, faceplate_coords=True, rotation_deg=0):
        """Place component and register with collision tracker.

        faceplate_coords=True means x/y are in faceplate space.
        """
        nonlocal placed
        if addr not in addr_map:
            warnings.append(addr)
            return
        fp = addr_map[addr]
        px = x_mm - ox if faceplate_coords else x_mm
        py = y_mm - oy if faceplate_coords else y_mm
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(px), pcbnew.FromMM(py)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        if rotation_deg:
            fp.SetOrientationDegrees(rotation_deg)
        # Register actual bounding box with collision tracker
        bbox = fp.GetBoundingBox(False, False)
        bx1 = pcbnew.ToMM(bbox.GetLeft())
        by1 = pcbnew.ToMM(bbox.GetTop())
        bx2 = pcbnew.ToMM(bbox.GetRight())
        by2 = pcbnew.ToMM(bbox.GetBottom())
        is_through = is_tht_fn(fp, pcbnew)
        side = "F" if front else "B"
        tracker.register_bbox(bx1, by1, bx2, by2, side, is_through, label=addr)
        tracker.register_label(fp, pcbnew, side)
        placed += 1
        placed_addrs.add(addr)

    # --- Through-hole components (front side, from panel layout) ---

    # Jacks -- all placed at positions from panel-layout.json.
    jack_rotation = layout["constants"].get("jack_rotation_deg", 0)

    # Jacks -- utility (non-MIDI)
    utility_addr_map = {
        "clk_in": "jacks.j_clk_in",
        "clk_out": "jacks.j_clk_out",
        "rst_in": "jacks.j_rst_in",
        "rst_out": "jacks.j_rst_out",
        "midi_in": "midi.jack_in",
        "midi_out": "midi.jack_out",
    }
    for jack in layout["jacks"]["utility"]:
        if jack["id"] in ("midi_in", "midi_out"):
            continue  # placed separately below
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place(addr, jack["x_mm"], jack["y_mm"],
                  rotation_deg=jack_rotation)

    # Jacks -- clock/reset
    clock_positions = {}
    for jack in layout["jacks"].get("clock", []):
        addr = utility_addr_map.get(jack["id"])
        clock_positions[jack["id"]] = (jack["x_mm"], jack["y_mm"])
        if addr:
            place(addr, jack["x_mm"], jack["y_mm"],
                  rotation_deg=jack_rotation)

    # MIDI jacks
    for jack in layout["jacks"].get("utility", []):
        if jack["id"] not in ("midi_in", "midi_out"):
            continue
        addr = utility_addr_map[jack["id"]]
        place(addr, jack["x_mm"], jack["y_mm"],
              rotation_deg=jack_rotation)

    # Jacks -- output (gate1..4, pitch1..4, vel1..4, mod1..4)
    for jack in layout["jacks"]["output"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"],
              rotation_deg=jack_rotation)

    # Jacks -- CV input
    for jack in layout["jacks"]["cv_input"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"],
              rotation_deg=jack_rotation)

    # Buttons -- track (t1..t4)
    for btn in layout["buttons"]["track"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- subtrack (gate, pitch, vel, mod)
    for btn in layout["buttons"]["subtrack"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Button -- pat (single item)
    pat = layout["buttons"].get("pat")
    if pat:
        place(f"buttons.btn_{pat['id']}", pat["x_mm"], pat["y_mm"])

    # Buttons -- feature (mute, route, drift, trns/xpose, var)
    feature_addr_map = {"trns": "xpose"}  # layout uses "trns", ato uses "xpose"
    for btn in layout["buttons"]["feature"]:
        ato_id = feature_addr_map.get(btn["id"], btn["id"])
        addr = f"buttons.btn_{ato_id}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- step (step1..step16)
    for btn in layout["buttons"]["step"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- transport (play, reset, settings)
    for btn in layout["buttons"].get("transport", []):
        if btn["id"] == "settings":
            addr = "buttons.btn_settings"
        else:
            addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- control strip (back, rand, clr)
    for btn in layout["buttons"].get("control_strip", []):
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Encoders
    for enc in layout["encoders"]:
        place(enc["id"], enc["x_mm"], enc["y_mm"])

    # SD card slot (front side, protrudes through faceplate cutout)
    # Try panel-layout first, fall back to component-map
    sd = layout.get("connectors", {}).get("sd_card", {})
    if "x_mm" not in sd or "y_mm" not in sd:
        sd = comp_map.get("connectors", {}).get("sd_card", {})
    if "x_mm" in sd and "y_mm" in sd:
        place("sd", sd["x_mm"], sd["y_mm"])

    # --- SMD components (back side) ---
    # Group unplaced SMD parts by their module prefix, then lay them out
    # in functional zones on the back of the board.
    # Convert faceplate coordinates to PCB coordinates for zone references
    jack_zone_x = layout["jacks"]["output"][0]["x_mm"] - ox
    step_x = layout["buttons"]["step"][0]["x_mm"] - ox
    center_x = w_mm / 2

    # --- Named component placement (back side) ---
    # All positions in PCB coords. Must avoid front-side THT pin areas.
    #
    # Front-side THT map (PCB coords):
    #   Track buttons:   x≈5.8,  y≈9..52
    #   Subtrack buttons: x≈100, y≈9..41
    #   Feature buttons:  x≈110, y≈9..52
    #   Transport buttons: x≈134, y≈10..34
    #   Step buttons:     x≈17..89, y≈88..98 (two rows)
    #   Encoders:         x≈11,y≈73  and  x≈105,y≈73
    #   Control strip:   x≈99..120, y≈93 (between step rows)
    #   Utility jacks:   x≈148..172, y≈10..45
    #   Output jacks:    x≈117..172, y≈48..99
    #   CV input jacks:  x≈117..172, y≈98..113

    lcd = layout.get("lcd_cutout", {})
    lcd_pcb_cx = lcd.get("center_x_mm", 54.78) - ox
    lcd_bottom_pcb = lcd.get("center_y_mm", 39.89) - oy + lcd.get("height_mm", 48.96) / 2

    # Board-to-board connector headers and other named positions from config.
    config = load_board_config()
    named_pos = config["boards"]["control"]["placement"].get("named_positions", {})
    for addr, pos in named_pos.items():
        place(addr, pos["x"], pos["y"], front=pos["front"], faceplate_coords=False)

    # FPC connector for display — front side, vertically centered with LCD.
    # Rotated 90° so flatband cable enters from the side.
    lcd_pcb_cy = lcd.get("center_y_mm", 39.89) - oy
    place("lcd_fpc", lcd_pcb_cx, lcd_pcb_cy, front=True, faceplate_coords=False, rotation_deg=90)

    # --- Exclusion zones ---
    # LCD display: SMDs can go on the front side in the screen area (they're
    # flat enough to fit under the display glass). No front-side zone exclusion
    # needed — THT components are at fixed faceplate positions and won't land
    # in the LCD area. The FPC connector is already registered as a collision
    # rect from the place() call above.

    # M3 standoff mounting holes — NPTH 3.2mm drill at standoff positions
    # These are in faceplate coords; convert to PCB coords.
    standoffs = comp_map.get("standoffs", [])
    standoff_drill = comp_map.get("footprints", {}).get("m3_standoff", {}).get("drill_mm", 3.2)
    standoff_clearance = comp_map.get("footprints", {}).get("m3_standoff", {}).get("clearance_mm", 6.0)
    for so in standoffs:
        so_pcb_x = so["x_mm"] - ox
        so_pcb_y = so["y_mm"] - oy
        # Create NPTH footprint on the board
        fp = pcbnew.FOOTPRINT(board)
        fp.SetReference(f"SO_{so['id'].upper()}")
        fp.SetValue("M3_Standoff")
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(so_pcb_x), pcbnew.FromMM(so_pcb_y)))
        fp.SetAttributes(pcbnew.FP_EXCLUDE_FROM_POS_FILES | pcbnew.FP_EXCLUDE_FROM_BOM)
        pad = pcbnew.PAD(fp)
        pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
        pad.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
        pad.SetDrillSize(pcbnew.VECTOR2I(pcbnew.FromMM(standoff_drill), pcbnew.FromMM(standoff_drill)))
        pad.SetSize(pcbnew.VECTOR2I(pcbnew.FromMM(standoff_drill), pcbnew.FromMM(standoff_drill)))
        fp.Add(pad)
        board.Add(fp)
        # Register exclusion zone for placement
        tracker.register(so_pcb_x, so_pcb_y, standoff_clearance, standoff_clearance,
                         "both", is_tht=False, label=f"standoff_{so['id']}")
    if standoffs:
        print(f"  {len(standoffs)} standoff mounting holes placed + exclusion zones registered ({standoff_clearance}mm)")

    tht_count = sum(1 for a in placed_addrs
                    if a in addr_map and is_tht_fn(addr_map[a], pcbnew))
    smd_count = len(placed_addrs) - tht_count
    standoff_count = len(standoffs)
    print(f"  Collision tracker: {tht_count} THT(both) + "
          f"{smd_count} SMD(sided) + {standoff_count} standoff(both) = {tracker.count} entries")

    # --- Zone layout ---
    # Board: 177.88 x 106.5mm (PCB coords).
    # LCD cutout: ~14..92 x ~3..56 (with margin) -- upper left, ~44% of board
    # PGA2350:   ~91..119 x ~26..54 (with margin) -- upper center-right
    #
    # Available back-side area:
    #   Bottom strip: x=3..175, y=57..103 (full width, 172mm x 46mm)
    #   Right strip:  x=120..175, y=3..54  (55mm x 51mm)
    #
    # Zone layout (PCB coords, back side):
    #   +------+-----------+--------+-----+----------+
    #   |      |LCD CUTOUT | PGA    |midi | dac      |  0
    #   |      |(no-place) |        |     |          |
    #   |      |           |        |     |          |
    #   +------+-----------+--------+-----+----------+  57
    #   |display| buttons  |  mcu   |     jacks      |
    #   +------+-----------+--------+-----------------+  80
    #   |power | _top      |  leds  |                 |
    #   +------+-----------+--------+-----------------+ 104
    #   0      30          75      120               178

    # --- Dynamic zone placement ---
    # Instead of hardcoded zones, dynamically find the largest free areas
    # on the back side and fill them. The CollisionTracker already blocks
    # THT pin areas, so SMDs naturally flow into available gaps.

    # Group unplaced components by module prefix
    module_prefixes = ["leds.", "buttons.", "connector.", "display.", "midi.", "jacks."]
    zone_groups = {prefix: [] for prefix in module_prefixes}
    zone_groups["_top"] = []

    for addr in addr_map:
        if addr in placed_addrs:
            continue
        assigned = False
        for prefix in module_prefixes:
            if addr.startswith(prefix):
                zone_groups[prefix].append(addr)
                assigned = True
                break
        if not assigned:
            zone_groups["_top"].append(addr)

    # Build connectivity graph for netlist-aware placement
    all_smd_addrs = []
    for addrs in zone_groups.values():
        all_smd_addrs.extend(addrs)
    power_nets = identify_power_nets(board)
    conn_graph = build_connectivity_graph(board, all_smd_addrs, addr_map, power_nets)
    print(f"  Power nets filtered: {len(power_nets)}")
    print(f"  Connectivity edges: {sum(len(v) for v in conn_graph.values()) // 2}")

    ic_pin_threshold = 5
    ic_spacing = 10.0
    passive_spacing = 5.5

    # Per-module IC spacing overrides from config
    module_ic_spacing = config["boards"]["control"]["placement"].get("module_ic_spacing", {})

    def classify_component(addr):
        fp = addr_map.get(addr)
        if not fp:
            return "passive"
        return "ic" if len(list(fp.Pads())) >= ic_pin_threshold else "passive"

    def compute_adaptive_spacing(rect_area, addrs, base_spacing):
        """Scale spacing based on how much free area is available vs component area.

        Returns (adapted_spacing, scale_factor) where scale_factor is 1.0 for
        tight fits and up to 2.5 for spacious areas.
        """
        total_comp_area = 0.0
        for addr in addrs:
            fp = addr_map.get(addr)
            if fp:
                needs_flip = fp.GetLayer() == board.GetLayerID("F.Cu")
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                fw, fh, _, _ = extract_footprint_dims(fp, pcbnew)
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                total_comp_area += fw * fh

        if total_comp_area == 0:
            return base_spacing, 1.0

        ratio = rect_area / total_comp_area

        if ratio < 1.5:
            scale = 1.0
        elif ratio > 2.0:
            scale = min(ratio / 2.0, 2.5)
        else:
            # Linear interpolation between 1.0 and 1.25 for ratio 1.5–2.0
            t = (ratio - 1.5) / 0.5
            scale = 1.0 + t * 0.25

        return base_spacing * scale, scale

    def place_in_rect(parts, zx, zy, zw, zh, spacing, label="", front=False,
                       label_aware=False):
        """Place parts in a grid within a rectangle, using collision-free search.

        When label_aware=True (ICs), the collision search uses an inflated
        bounding box that includes the reference designator text, so labels
        don't get clipped by neighboring components.
        """
        if not parts:
            return
        cols = max(1, int((zw - 1) / spacing) + 1)
        rows_needed = (len(parts) + cols - 1) // cols
        grid_w = (cols - 1) * spacing
        start_x = zx + (zw - grid_w) / 2
        start_y = zy + 1

        for i, addr in enumerate(parts):
            fp = addr_map.get(addr)
            if not fp:
                continue
            # Measure dims AFTER flipping to target side (matches what place() registers)
            needs_flip = (not front) and fp.GetLayer() == board.GetLayerID("F.Cu")
            if needs_flip:
                fp.Flip(fp.GetPosition(), False)
            fw, fh, _, _ = extract_footprint_dims(fp, pcbnew)
            is_through = is_tht_fn(fp, pcbnew)

            # For ICs: inflate search envelope to include ref text
            if label_aware:
                ref_bbox = get_ref_text_bbox(fp, pcbnew)
                if ref_bbox:
                    body_bbox = fp.GetBoundingBox(False, False)
                    bx1 = pcbnew.ToMM(body_bbox.GetLeft())
                    by1 = pcbnew.ToMM(body_bbox.GetTop())
                    bx2 = pcbnew.ToMM(body_bbox.GetRight())
                    by2 = pcbnew.ToMM(body_bbox.GetBottom())
                    # Combined envelope of body + label
                    combined_w = max(bx2, ref_bbox[2]) - min(bx1, ref_bbox[0])
                    combined_h = max(by2, ref_bbox[3]) - min(by1, ref_bbox[1])
                    fw = max(fw, combined_w)
                    fh = max(fh, combined_h)

            if needs_flip:
                fp.Flip(fp.GetPosition(), False)  # flip back — place() will flip again

            col = i % cols
            row = i // cols
            if row % 2 == 1:
                col = cols - 1 - col
            desired_x = start_x + col * spacing
            desired_y = start_y + row * spacing

            result = tracker.find_free(
                desired_x, desired_y, fw, fh,
                side="B", is_tht=is_through,
                zone_bounds=(zx, zy, zw, zh),
                step=0.5,
            )
            if result is None:
                x, y = desired_x, desired_y
            else:
                x, y = result
            place(addr, x, y, front=False, faceplate_coords=False)

    def place_module_dynamic(addrs, label):
        """Place a module's components into the largest free area, then rescan."""
        if not addrs:
            return

        ics = size_sort(
            [a for a in addrs if classify_component(a) == "ic"], addr_map, pcbnew)
        passives = size_sort(
            [a for a in addrs if classify_component(a) == "passive"], addr_map, pcbnew)

        # Separate THT components from SMD — THT need both-sides-free placement
        tht_ics = [a for a in ics if is_tht_fn(addr_map[a], pcbnew)]
        smd_ics = [a for a in ics if not is_tht_fn(addr_map[a], pcbnew)]
        tht_passives = [a for a in passives if is_tht_fn(addr_map[a], pcbnew)]
        smd_passives = [a for a in passives if not is_tht_fn(addr_map[a], pcbnew)]

        # Place THT components first — they need space clear on BOTH sides.
        # Place each THT component individually near its connected peers.
        #
        # Key fix: find_free assumes (cx, cy) is the bbox CENTER, but footprint
        # reference points may be offset (e.g. SIP-9 ref at pin 1 = top).
        # We compute the bbox center offset and adjust search accordingly.
        if tht_ics or tht_passives:
            for addr in tht_ics + tht_passives:
                fp = addr_map.get(addr)
                if not fp:
                    continue
                needs_flip = fp.GetLayer() == board.GetLayerID("F.Cu")
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                fw, fh, _, _ = extract_footprint_dims(fp, pcbnew)

                # Compute bbox center offset from footprint reference point
                orig_pos = fp.GetPosition()
                fp.SetPosition(pcbnew.VECTOR2I(0, 0))
                bbox = fp.GetBoundingBox(False, False)
                off_x = (pcbnew.ToMM(bbox.GetLeft()) + pcbnew.ToMM(bbox.GetRight())) / 2
                off_y = (pcbnew.ToMM(bbox.GetTop()) + pcbnew.ToMM(bbox.GetBottom())) / 2
                fp.SetPosition(orig_pos)

                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)

                # Target: near connected components (average position)
                neighbors = conn_graph.get(addr, [])
                if neighbors:
                    positions = []
                    for n in neighbors:
                        nfp = addr_map.get(n)
                        if nfp:
                            npos = nfp.GetPosition()
                            positions.append((pcbnew.ToMM(npos.x) - ox,
                                              pcbnew.ToMM(npos.y) - oy))
                    if positions:
                        target_x = sum(p[0] for p in positions) / len(positions)
                        target_y = sum(p[1] for p in positions) / len(positions)
                    else:
                        target_x, target_y = w_mm / 2, h_mm / 2
                else:
                    target_x, target_y = w_mm / 2, h_mm / 2

                # Search at bbox-center position (not ref point)
                search_cx = target_x + off_x
                search_cy = target_y + off_y

                result = tracker.find_free(
                    search_cx, search_cy, fw, fh,
                    side="B", is_tht=True, step=0.5)
                if result is None:
                    found_cx, found_cy = search_cx, search_cy
                else:
                    found_cx, found_cy = result

                # Convert found bbox center back to ref point for placement
                place_x = found_cx - off_x
                place_y = found_cy - off_y

                place(addr, place_x, place_y, front=False, faceplate_coords=False)

        # Place SMD components — connectivity-aware, try both sides, pick closer.
        board_zone = (0, 0, w_mm, h_mm)
        for addr in smd_ics + smd_passives:
            fp = addr_map.get(addr)
            if not fp:
                continue
            needs_flip = (fp.GetLayer() == board.GetLayerID("F.Cu"))
            if needs_flip:
                fp.Flip(fp.GetPosition(), False)
            fw, fh, _, _ = extract_footprint_dims(fp, pcbnew)
            is_through = is_tht_fn(fp, pcbnew)
            if needs_flip:
                fp.Flip(fp.GetPosition(), False)

            # Target: centroid of placed connected neighbors + repulsion
            neighbors = conn_graph.get(addr, {})
            positions = []
            for n in neighbors:
                nfp = addr_map.get(n)
                if nfp and n in placed_addrs:
                    npos = nfp.GetPosition()
                    positions.append((pcbnew.ToMM(npos.x) - ox,
                                      pcbnew.ToMM(npos.y) - oy))
            if positions:
                tx = sum(p[0] for p in positions) / len(positions)
                ty = sum(p[1] for p in positions) / len(positions)
            else:
                tx, ty = w_mm / 2, h_mm / 2

            # Apply repulsion from nearby placed components
            rx, ry = tracker.repulsion_offset(tx, ty)
            tx = max(0, min(w_mm, tx + rx))
            ty = max(0, min(h_mm, ty + ry))

            # Search both sides, pick whichever is closer to target
            result_f = tracker.find_free(tx, ty, fw, fh, "F", is_through, board_zone, step=0.5)
            result_b = tracker.find_free(tx, ty, fw, fh, "B", is_through, board_zone, step=0.5)
            fx, fy = result_f if result_f else (tx, ty)
            bx, by = result_b if result_b else (tx, ty)
            dist_f = (fx - tx) ** 2 + (fy - ty) ** 2
            dist_b = (bx - tx) ** 2 + (by - ty) ** 2

            if dist_f <= dist_b:
                place(addr, fx + ox, fy + oy, front=True, faceplate_coords=True)
            else:
                place(addr, bx + ox, by + oy, front=False, faceplate_coords=True)

        n_ics = len(ics)
        n_pass = len(passives)
        n_tht = len(tht_ics) + len(tht_passives)
        n_smd = len(smd_ics) + len(smd_passives)
        tht_note = f" ({n_tht} THT)" if n_tht else ""
        print(f"    {label:12s}: {n_ics:2d} ICs + {n_pass:2d} passives"
              f" ({n_smd} SMD connectivity-placed){tht_note}")

    # Place each module group, largest modules first (they need the most space)
    module_order = sorted(zone_groups.keys(),
                          key=lambda k: len(zone_groups[k]), reverse=True)
    for prefix in module_order:
        addrs = zone_groups[prefix]
        if addrs:
            place_module_dynamic(addrs, prefix)

    # Print summary
    print(f"  Placed {placed}/{len(addr_map)} components")
    if warnings:
        print(f"  {len(warnings)} addresses not found:")
        for w in warnings:
            print(f"    - {w}")

    # Estimate total wire length (Manhattan distance of non-power net connections)
    net_pads = defaultdict(list)
    for fp in board.GetFootprints():
        pos = fp.GetPosition()
        px, py = pcbnew.ToMM(pos.x), pcbnew.ToMM(pos.y)
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name and net_name not in power_nets:
                net_pads[net_name].append((px, py))
    total_wire = 0.0
    for net_name, pads in net_pads.items():
        if len(pads) < 2:
            continue
        cx = sum(p[0] for p in pads) / len(pads)
        cy = sum(p[1] for p in pads) / len(pads)
        for px, py in pads:
            total_wire += abs(px - cx) + abs(py - cy)
    print(f"  Estimated wire length (non-power): {total_wire:.0f} mm")

    # --- Validate placement using CollisionTracker ---
    # The tracker already has all components registered from place() calls.
    # Now do a final independent verification scan directly from KiCad footprints.

    def fp_label(fp):
        if fp.HasFieldByName("atopile_address"):
            return fp.GetFieldText("atopile_address")
        return fp.GetReference()

    footprints = list(board.GetFootprints())

    # 1. Out-of-bounds check
    oob_margin = 1.0
    oob = []
    for fp in footprints:
        bbox = fp.GetBoundingBox(False, False)
        x1 = pcbnew.ToMM(bbox.GetLeft())
        y1 = pcbnew.ToMM(bbox.GetTop())
        x2 = pcbnew.ToMM(bbox.GetRight())
        y2 = pcbnew.ToMM(bbox.GetBottom())
        if x1 < -oob_margin or y1 < -oob_margin or x2 > w_mm + oob_margin or y2 > h_mm + oob_margin:
            oob.append((fp_label(fp), x1, y1, x2, y2))
    if oob:
        print(f"  WARNING: {len(oob)} components extend outside board ({w_mm}x{h_mm}mm):")
        for label, x1, y1, x2, y2 in oob[:20]:
            print(f"    - {label} bbox ({x1:.1f},{y1:.1f})-({x2:.1f},{y2:.1f})")
    else:
        print(f"  Bounds check: PASS ({len(footprints)} footprints within board)")

    # 2. Overlap check — independent scan (not relying on tracker data)
    # This catches any overlaps the tracker might have missed or allowed.
    min_overlap_mm2 = 0.5
    fp_data = []
    for fp in footprints:
        bbox = fp.GetBoundingBox(False, False)
        fp_data.append((
            fp_label(fp),
            (pcbnew.ToMM(bbox.GetLeft()), pcbnew.ToMM(bbox.GetTop()),
             pcbnew.ToMM(bbox.GetRight()), pcbnew.ToMM(bbox.GetBottom())),
            "F" if fp.GetLayer() == board.GetLayerID("F.Cu") else "B",
            is_tht_fn(fp, pcbnew),
        ))

    overlaps = []
    for i in range(len(fp_data)):
        label_a, bbox_a, side_a, tht_a = fp_data[i]
        for j in range(i + 1, len(fp_data)):
            label_b, bbox_b, side_b, tht_b = fp_data[j]
            # Same side: always check. Cross side: only if one is THT.
            if side_a == side_b:
                kind = f"same-side ({side_a})"
            elif tht_a or tht_b:
                kind = "THT cross-side"
            else:
                continue
            dx = min(bbox_a[2], bbox_b[2]) - max(bbox_a[0], bbox_b[0])
            dy = min(bbox_a[3], bbox_b[3]) - max(bbox_a[1], bbox_b[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= min_overlap_mm2:
                    overlaps.append((label_a, label_b, kind, area))

    n_overlaps = len(overlaps)
    if n_overlaps == 0:
        print(f"  Overlap check: PASS (0 collisions among {len(fp_data)} footprints)")
    else:
        overlaps.sort(key=lambda x: -x[3])
        print(f"  Overlap check: {n_overlaps} overlaps")
        for la, lb, kind, area in overlaps[:20]:
            print(f"    - {la} <-> {lb} ({kind}, {area:.1f}mm²)")

    # Label overlap check — informational only (doesn't block placement)
    label_data = []
    for fp in footprints:
        ref_bbox = get_ref_text_bbox(fp, pcbnew)
        if ref_bbox:
            side = "F" if fp.GetLayer() == board.GetLayerID("F.Cu") else "B"
            label_data.append((fp.GetReference(), ref_bbox, side))

    label_overlaps = []
    for ref_name, lbox, lside in label_data:
        for fp_name, fbox, fside, tht in fp_data:
            if lside != fside and not tht:
                continue
            if ref_name in fp_name:
                continue
            dx = min(lbox[2], fbox[2]) - max(lbox[0], fbox[0])
            dy = min(lbox[3], fbox[3]) - max(lbox[1], fbox[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= 0.3:
                    label_overlaps.append((
                        f"label:{ref_name}", fp_name, "label-body", area))

    for i in range(len(label_data)):
        ref_a, lbox_a, side_a = label_data[i]
        for j in range(i + 1, len(label_data)):
            ref_b, lbox_b, side_b = label_data[j]
            if side_a != side_b:
                continue
            dx = min(lbox_a[2], lbox_b[2]) - max(lbox_a[0], lbox_b[0])
            dy = min(lbox_a[3], lbox_b[3]) - max(lbox_a[1], lbox_b[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= 0.3:
                    label_overlaps.append((
                        f"label:{ref_a}", f"label:{ref_b}", "label-label", area))

    if label_overlaps:
        label_overlaps.sort(key=lambda x: -x[3])
        print(f"  Label overlaps: {len(label_overlaps)} (informational)")
        for la, lb, kind, area in label_overlaps[:15]:
            print(f"    - {la} <-> {lb} ({kind}, {area:.1f}mm²)")
    else:
        print(f"  Label overlaps: 0 (clean)")

    board.Save(output_pcb)
    n_fixed = regenerate_duplicate_uuids(output_pcb)
    if n_fixed:
        print(f"  Fixed {n_fixed} duplicate pad UUIDs")
    print(f"  Saved to {output_pcb}")
    return n_overlaps


def detect_board_type(input_pcb):
    """Detect board type from PCB filename. Returns 'main' or 'control'."""
    basename = os.path.basename(input_pcb).lower()
    if "main" in basename:
        return "main"
    return "control"


# ---------------------------------------------------------------------------
# Variant-aware placement (strategy system)
# ---------------------------------------------------------------------------


def _setup_board_outline(board, w_mm, h_mm, pcbnew):
    """Set board edge cuts and copper layer count."""
    board.SetCopperLayerCount(4)
    edge_layer = board.GetLayerID("Edge.Cuts")
    for x1, y1, x2, y2 in [
        (0, 0, w_mm, 0), (w_mm, 0, w_mm, h_mm),
        (w_mm, h_mm, 0, h_mm), (0, h_mm, 0, 0),
    ]:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)


def _build_addr_map(board):
    """Build lookup from atopile_address to footprint."""
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp
    return addr_map


def _place_fixed_main(board, addr_map, config, pcbnew):
    """Place fixed components on main board. Returns set of fixed addresses
    and dict of address → Placement."""
    from placement.helpers import extract_footprint_dims, is_tht as is_tht_fn
    from placement.strategies import Placement

    main_config = config["boards"]["main"]
    board_w = main_config["dimensions"]["width_mm"]
    board_h = main_config["dimensions"]["height_mm"]
    named_pos = main_config["placement"].get("named_positions", {})

    fixed_placements = {}

    for addr, pos in named_pos.items():
        if addr not in addr_map:
            continue
        fp = addr_map[addr]
        x, y = pos["x"], pos["y"]
        front = pos["front"]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        fixed_placements[addr] = Placement(x=x, y=y,
                                            side="F" if front else "B")

    # USB-C — front side, below center (swapped Y with bootsel)
    usb_addr = "usb"
    if usb_addr in addr_map:
        fp = addr_map[usb_addr]
        usb_x, usb_y = 5.0, board_h / 2 + 10
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(usb_x),
                                        pcbnew.FromMM(usb_y)))
        if fp.GetLayer() != board.GetLayerID("F.Cu"):
            fp.Flip(fp.GetPosition(), False)
        fp.SetOrientationDegrees(90)
        fixed_placements[usb_addr] = Placement(x=usb_x, y=usb_y, side="F",
                                                rotation=90)

    # Bootsel button — front side, centered (swapped Y with USB-C)
    bootsel_addr = "mcu.sw_bootsel"
    if bootsel_addr in addr_map:
        fp = addr_map[bootsel_addr]
        bx, by = 5.0, board_h / 2
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(bx), pcbnew.FromMM(by)))
        if fp.GetLayer() != board.GetLayerID("F.Cu"):
            fp.Flip(fp.GetPosition(), False)
        fixed_placements[bootsel_addr] = Placement(x=bx, y=by, side="F")

    return fixed_placements


def _place_fixed_control(board, addr_map, config, pcbnew):
    """Place fixed components on control board (THT from panel layout +
    named positions). Returns dict of address → Placement."""
    from placement.strategies import Placement

    layout = load_layout()
    comp_map = load_component_map()
    pcb_dims = comp_map["pcb"]
    ox = pcb_dims["origin_x_mm"]
    oy = pcb_dims["origin_y_mm"]

    fixed_placements = {}

    def place_fixed(addr, x_mm, y_mm, front=True, faceplate_coords=True,
                    rotation_deg=0):
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        px = x_mm - ox if faceplate_coords else x_mm
        py = y_mm - oy if faceplate_coords else y_mm
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(px), pcbnew.FromMM(py)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        if rotation_deg:
            fp.SetOrientationDegrees(rotation_deg)
        fixed_placements[addr] = Placement(
            x=px, y=py, side="F" if front else "B", rotation=rotation_deg,
        )

    # --- THT components from panel layout ---
    jack_rotation = layout["constants"].get("jack_rotation_deg", 0)

    utility_addr_map = {
        "clk_in": "jacks.j_clk_in", "clk_out": "jacks.j_clk_out",
        "rst_in": "jacks.j_rst_in", "rst_out": "jacks.j_rst_out",
        "midi_in": "midi.jack_in", "midi_out": "midi.jack_out",
    }
    for jack in layout["jacks"]["utility"]:
        if jack["id"] in ("midi_in", "midi_out"):
            continue
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place_fixed(addr, jack["x_mm"], jack["y_mm"],
                        rotation_deg=jack_rotation)
    for jack in layout["jacks"].get("clock", []):
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place_fixed(addr, jack["x_mm"], jack["y_mm"],
                        rotation_deg=jack_rotation)
    for jack in layout["jacks"].get("utility", []):
        if jack["id"] not in ("midi_in", "midi_out"):
            continue
        addr = utility_addr_map[jack["id"]]
        place_fixed(addr, jack["x_mm"], jack["y_mm"],
                    rotation_deg=jack_rotation)
    for jack in layout["jacks"]["output"]:
        place_fixed(f"jacks.j_{jack['id']}", jack["x_mm"], jack["y_mm"],
                    rotation_deg=jack_rotation)
    for jack in layout["jacks"]["cv_input"]:
        place_fixed(f"jacks.j_{jack['id']}", jack["x_mm"], jack["y_mm"],
                    rotation_deg=jack_rotation)

    # Buttons
    for btn in layout["buttons"]["track"]:
        place_fixed(f"buttons.btn_{btn['id']}", btn["x_mm"], btn["y_mm"])
    for btn in layout["buttons"]["subtrack"]:
        place_fixed(f"buttons.btn_{btn['id']}", btn["x_mm"], btn["y_mm"])
    pat = layout["buttons"].get("pat")
    if pat:
        place_fixed(f"buttons.btn_{pat['id']}", pat["x_mm"], pat["y_mm"])
    feature_addr_map = {"trns": "xpose"}
    for btn in layout["buttons"]["feature"]:
        ato_id = feature_addr_map.get(btn["id"], btn["id"])
        place_fixed(f"buttons.btn_{ato_id}", btn["x_mm"], btn["y_mm"])
    for btn in layout["buttons"]["step"]:
        place_fixed(f"buttons.btn_{btn['id']}", btn["x_mm"], btn["y_mm"])
    for btn in layout["buttons"].get("transport", []):
        if btn["id"] == "settings":
            place_fixed("buttons.btn_settings", btn["x_mm"], btn["y_mm"])
        else:
            place_fixed(f"buttons.btn_{btn['id']}", btn["x_mm"], btn["y_mm"])
    for btn in layout["buttons"].get("control_strip", []):
        place_fixed(f"buttons.btn_{btn['id']}", btn["x_mm"], btn["y_mm"])

    # Encoders
    for enc in layout["encoders"]:
        place_fixed(enc["id"], enc["x_mm"], enc["y_mm"])

    # SD card slot
    sd = layout.get("connectors", {}).get("sd_card", {})
    if "x_mm" not in sd or "y_mm" not in sd:
        sd = comp_map.get("connectors", {}).get("sd_card", {})
    if "x_mm" in sd and "y_mm" in sd:
        place_fixed("sd", sd["x_mm"], sd["y_mm"])

    # Named positions from config (connectors, MIDI opto, etc.)
    named_pos = config["boards"]["control"]["placement"].get(
        "named_positions", {})
    for addr, pos in named_pos.items():
        place_fixed(addr, pos["x"], pos["y"], front=pos["front"],
                    faceplate_coords=False)

    # FPC connector for display
    lcd = layout.get("lcd_cutout", {})
    lcd_pcb_cx = lcd.get("center_x_mm", 54.78) - ox
    lcd_pcb_cy = lcd.get("center_y_mm", 39.89) - oy
    place_fixed("lcd_fpc", lcd_pcb_cx, lcd_pcb_cy, front=True,
                faceplate_coords=False, rotation_deg=90)

    return fixed_placements


def _extract_component_info(addr, fp, pcbnew, power_nets):
    """Extract ComponentInfo from a pcbnew footprint."""
    from placement.helpers import extract_footprint_dims, is_tht as is_tht_fn, \
        get_component_nets
    from placement.strategies import ComponentInfo

    w, h, cx_off, cy_off = extract_footprint_dims(fp, pcbnew)
    tht = is_tht_fn(fp, pcbnew)
    pin_count = len(list(fp.Pads()))
    nets = get_component_nets(fp, power_nets)
    return ComponentInfo(
        address=addr, width=w, height=h, is_tht=tht,
        pin_count=pin_count, nets=nets,
        cx_offset=cx_off, cy_offset=cy_off,
    )


def place_variant(input_pcb, output_pcb, board_type, variant_name):
    """Place components using a named variant from board-config.json.

    Loads the strategy and params for the variant, places fixed components
    using board-specific logic, then delegates free components to the strategy.
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python.")
        sys.exit(1)

    # Import strategy system (absolute imports — script adds scripts/ to sys.path)
    from placement.helpers import (
        identify_power_nets, build_net_graph, regenerate_duplicate_uuids,
    )
    from placement.strategies import AntiAffinityRule, BoardContext, get_strategy
    # Ensure all strategies are registered
    from placement.strategies import constructive, force_directed, sa_refine  # noqa: F401

    config = load_board_config()

    # Look up variant config
    placement_cfg = config.get("placement", {})
    board_placement = config["boards"][board_type]["placement"]
    variants = board_placement.get("variants", placement_cfg.get("variants", []))
    variant_cfg = None
    for v in variants:
        if v["name"] == variant_name:
            variant_cfg = v
            break
    if variant_cfg is None:
        print(f"  ERROR: variant '{variant_name}' not found in config")
        sys.exit(1)

    algorithm = variant_cfg["algorithm"]
    params = variant_cfg.get("params", {})

    print(f"  Variant: {variant_name} (algorithm={algorithm})")
    print(f"  Params: {params}")

    # Load board
    board = pcbnew.LoadBoard(input_pcb)
    addr_map = _build_addr_map(board)

    if not addr_map:
        print("  No components with atopile_address found.")
        board.Save(output_pcb)
        return

    # Board dimensions
    if board_type == "main":
        board_w = config["boards"]["main"]["dimensions"]["width_mm"]
        board_h = config["boards"]["main"]["dimensions"]["height_mm"]
    else:
        comp_map = load_component_map()
        pcb_dims = comp_map["pcb"]
        board_w = pcb_dims["width_mm"]
        board_h = pcb_dims["height_mm"]

    _setup_board_outline(board, board_w, board_h, pcbnew)

    # Place fixed components
    if board_type == "main":
        fixed_placements = _place_fixed_main(board, addr_map, config, pcbnew)
    else:
        fixed_placements = _place_fixed_control(board, addr_map, config,
                                                 pcbnew)

    print(f"  Fixed: {len(fixed_placements)} components")

    # Extract ComponentInfo for ALL components (fixed + free)
    power_nets = identify_power_nets(board)
    fixed_info = {}
    free_components = {}
    for addr, fp in addr_map.items():
        info = _extract_component_info(addr, fp, pcbnew, power_nets)
        if addr in fixed_placements:
            fixed_info[addr] = info
        else:
            free_components[addr] = info

    print(f"  Free: {len(free_components)} components")

    # Build net graph
    net_graph = build_net_graph(board, addr_map, power_nets)
    print(f"  Nets: {len(net_graph)} (non-power, 2+ connections)")

    # Parse anti-affinity rules from board config or top-level placement config
    anti_affinity_cfg = board_placement.get(
        "anti_affinity", placement_cfg.get("anti_affinity", []))
    anti_affinity_rules = [
        AntiAffinityRule(
            from_pattern=r["from"], to_pattern=r["to"], min_mm=r["min_mm"],
        )
        for r in anti_affinity_cfg
    ]
    if anti_affinity_rules:
        print(f"  Anti-affinity: {len(anti_affinity_rules)} rules")

    # Build context and run strategy
    smd_side = board_placement.get("smd_side", "both")
    ctx = BoardContext(
        width=board_w,
        height=board_h,
        fixed=fixed_placements,
        free=free_components,
        net_graph=net_graph,
        config=board_placement,
        fixed_info=fixed_info,
        anti_affinity=anti_affinity_rules,
        smd_side=smd_side,
    )

    strategy = get_strategy(algorithm)
    placements = strategy.place(ctx, params)

    # Check all free components were placed
    unplaced = [a for a in free_components if a not in placements]
    if unplaced:
        print(f"  FAIL: {len(unplaced)} components could not be placed: "
              f"{', '.join(unplaced[:5])}"
              f"{'...' if len(unplaced) > 5 else ''}")
        print(f"  Skipping variant {variant_name} — incomplete placement")
        sys.exit(1)

    # Validate placement: all components must be in bounds and overlap-free
    from placement.helpers import validate_placement, check_anti_affinity
    all_info = {**fixed_info, **free_components}
    tht_extra_val = board_placement.get("tht_extra_clearance_mm", 0.0)
    ok, out_of_bounds, overlapping = validate_placement(
        board_w, board_h, fixed_placements, placements, all_info,
        tht_extra_clearance=tht_extra_val,
    )
    if not ok:
        if out_of_bounds:
            print(f"  FAIL: {len(out_of_bounds)} components out of bounds: "
                  f"{', '.join(out_of_bounds[:5])}"
                  f"{'...' if len(out_of_bounds) > 5 else ''}")
        if overlapping:
            print(f"  FAIL: {len(overlapping)} components overlapping: "
                  f"{', '.join(overlapping[:5])}"
                  f"{'...' if len(overlapping) > 5 else ''}")
        print(f"  Skipping variant {variant_name} — invalid placement")
        sys.exit(1)

    # Check anti-affinity rules (warn, don't fail — strategies do best-effort)
    aa_violations = check_anti_affinity(placements, fixed_placements,
                                         anti_affinity_rules)
    if aa_violations:
        print(f"  WARNING: {len(aa_violations)} anti-affinity violations:")
        for a, b, dist, min_mm in aa_violations:
            print(f"    {a} <-> {b}: {dist}mm (min {min_mm}mm)")

    # Apply placements to pcbnew
    placed = 0
    for addr, p in placements.items():
        if addr not in addr_map:
            continue
        fp = addr_map[addr]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(p.x), pcbnew.FromMM(p.y)))
        target_front = p.side == "F"
        current_front = fp.GetLayer() == board.GetLayerID("F.Cu")
        if target_front != current_front:
            fp.Flip(fp.GetPosition(), False)
        if p.rotation:
            fp.SetOrientationDegrees(p.rotation)
        placed += 1

    print(f"  Strategy placed {placed} components")

    # Add standoffs for control board
    if board_type == "control":
        comp_map_data = load_component_map()
        standoffs = comp_map_data.get("standoffs", [])
        standoff_drill = comp_map_data.get("footprints", {}).get(
            "m3_standoff", {}).get("drill_mm", 3.2)
        pcb_dims = comp_map_data["pcb"]
        ox = pcb_dims["origin_x_mm"]
        oy = pcb_dims["origin_y_mm"]
        for so in standoffs:
            so_pcb_x = so["x_mm"] - ox
            so_pcb_y = so["y_mm"] - oy
            fp = pcbnew.FOOTPRINT(board)
            fp.SetReference(f"SO_{so['id'].upper()}")
            fp.SetValue("M3_Standoff")
            fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(so_pcb_x),
                                            pcbnew.FromMM(so_pcb_y)))
            fp.SetAttributes(pcbnew.FP_EXCLUDE_FROM_POS_FILES |
                             pcbnew.FP_EXCLUDE_FROM_BOM)
            pad = pcbnew.PAD(fp)
            pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
            pad.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
            pad.SetDrillSize(pcbnew.VECTOR2I(pcbnew.FromMM(standoff_drill),
                                              pcbnew.FromMM(standoff_drill)))
            pad.SetSize(pcbnew.VECTOR2I(pcbnew.FromMM(standoff_drill),
                                         pcbnew.FromMM(standoff_drill)))
            fp.Add(pad)
            board.Add(fp)
        if standoffs:
            print(f"  {len(standoffs)} standoff mounting holes placed")

    # Save and fix UUIDs
    board.Save(output_pcb)
    n_fixed = regenerate_duplicate_uuids(output_pcb)
    if n_fixed:
        print(f"  Fixed {n_fixed} duplicate pad UUIDs")
    print(f"  Saved to {output_pcb}")


def main():
    parser = argparse.ArgumentParser(
        description="Place components on KiCad PCB."
    )
    parser.add_argument(
        "--board",
        choices=["control", "main"],
        default=None,
        help="Board type: 'control' (panel layout) or 'main' (compact grid). "
             "Auto-detected from filename if not specified.",
    )
    parser.add_argument(
        "--variant",
        default=None,
        help="Variant name from board-config.json (enables strategy-based "
             "placement). Without this flag, uses legacy placement.",
    )
    parser.add_argument("input_pcb", help="Input .kicad_pcb file")
    parser.add_argument("output_pcb", nargs="?", default=None,
                        help="Output .kicad_pcb file")
    args = parser.parse_args()

    board_type = args.board or detect_board_type(args.input_pcb)
    print(f"  Board type: {board_type}")

    if args.variant:
        # Strategy-based variant placement
        output = args.output_pcb or args.input_pcb
        place_variant(args.input_pcb, output, board_type, args.variant)
    elif board_type == "main":
        place_main_board(args.input_pcb, args.output_pcb)
    else:
        place_components(args.input_pcb, args.output_pcb)


if __name__ == "__main__":
    # Add scripts/ to sys.path so absolute imports (placement.helpers, etc.) work
    # when this file is run directly as a script.
    _scripts_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if _scripts_dir not in sys.path:
        sys.path.insert(0, _scripts_dir)
    main()
