#!/usr/bin/env python3
"""Place components on KiCad PCB using positions from panel-layout.json.

Reads the .kicad_pcb generated by `ato build`, places through-hole components
at their faceplate positions, and groups SMD components near their connected
through-hole counterparts.

Usage:
    python place_components.py <input.kicad_pcb> [output.kicad_pcb]

Requires: KiCad's pcbnew Python module (available in KiCad installation or Docker).
"""

import json
import os
import sys

LAYOUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "panel-layout.json")


def load_layout():
    with open(LAYOUT_PATH) as f:
        return json.load(f)


def place_components(input_pcb, output_pcb=None):
    """Place components using pcbnew API."""
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run inside KiCad environment or Docker.")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    layout = load_layout()
    panel = layout["panel"]

    board = pcbnew.LoadBoard(input_pcb)

    # Set board outline
    w_mm = panel["width_mm"]
    h_mm = panel["height_mm"]
    edge_layer = board.GetLayerID("Edge.Cuts")

    # Create board outline rectangle
    seg_coords = [
        (0, 0, w_mm, 0),
        (w_mm, 0, w_mm, h_mm),
        (w_mm, h_mm, 0, h_mm),
        (0, h_mm, 0, 0),
    ]
    for x1, y1, x2, y2 in seg_coords:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Build a lookup from reference designator to footprint
    footprint_map = {}
    for fp in board.GetFootprints():
        ref = fp.GetReference()
        footprint_map[ref] = fp

    def place(ref, x_mm, y_mm, front=True):
        """Place a footprint at absolute position."""
        if ref not in footprint_map:
            print(f"  WARNING: {ref} not found on board")
            return
        fp = footprint_map[ref]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x_mm), pcbnew.FromMM(y_mm)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)

    # --- Through-hole components (front side, positions from panel layout) ---

    # Jacks
    for jack in layout["jacks"]["utility"]:
        ref_map = {
            "clk_in": "J_CLK_IN", "clk_out": "J_CLK_OUT",
            "rst_in": "J_RST_IN", "rst_out": "J_RST_OUT",
            "midi_in": "J_MIDI_IN", "midi_out": "J_MIDI_OUT",
        }
        ref = ref_map.get(jack["id"])
        if ref:
            place(ref, jack["x_mm"], jack["y_mm"])

    for jack in layout["jacks"]["output"]:
        ref = f"J_{jack['id'].upper()}"
        place(ref, jack["x_mm"], jack["y_mm"])

    for jack in layout["jacks"]["cv_input"]:
        ref = f"J_{jack['id'].upper()}"
        place(ref, jack["x_mm"], jack["y_mm"])

    # Buttons (TC002-RGB instances are in the ButtonScanner module)
    for btn in layout["buttons"]["track"]:
        ref = f"SW_{btn['id'].upper()}"
        place(ref, btn["x_mm"], btn["y_mm"])

    for btn in layout["buttons"]["subtrack"]:
        ref = f"SW_{btn['id'].upper()}"
        place(ref, btn["x_mm"], btn["y_mm"])

    for btn in layout["buttons"]["feature"]:
        ref = f"SW_{btn['id'].upper()}"
        place(ref, btn["x_mm"], btn["y_mm"])

    for btn in layout["buttons"]["step"]:
        ref = f"SW_{btn['id'].upper()}"
        place(ref, btn["x_mm"], btn["y_mm"])

    # Encoders
    for enc in layout["encoders"]:
        ref = f"ENC_{enc['id'].upper()}"
        place(ref, enc["x_mm"], enc["y_mm"])

    # --- SMD components (back side) ---
    # Place near their functional group.
    # These are rough placements; Freerouting will handle routing.

    jack_zone_x = layout["jacks"]["output"][0]["x_mm"]  # ~128mm

    # DACs + op-amps near output jacks (analog zone)
    place("U_DAC1", jack_zone_x - 15, 60, front=False)
    place("U_DAC2", jack_zone_x - 15, 80, front=False)
    place("U_OPAMP1", jack_zone_x - 8, 55, front=False)
    place("U_OPAMP2", jack_zone_x - 8, 67, front=False)
    place("U_OPAMP3", jack_zone_x - 8, 79, front=False)
    place("U_OPAMP4", jack_zone_x - 8, 91, front=False)

    # Shift registers near button area
    step_x = layout["buttons"]["step"][0]["x_mm"]  # ~19mm
    place("U_SR1", step_x + 10, 85, front=False)
    place("U_SR2", step_x + 30, 85, front=False)
    place("U_SR3", step_x + 50, 85, front=False)
    place("U_SR4", step_x + 70, 85, front=False)

    # LED drivers near button area
    place("U_TLC1", step_x + 10, 95, front=False)
    place("U_TLC2", step_x + 30, 95, front=False)
    place("U_TLC3", step_x + 50, 95, front=False)
    place("U_TLC4", step_x + 70, 95, front=False)

    # Pico module centered
    center_x = panel["width_mm"] / 2
    place("U_PICO", center_x, 50, front=False)

    # Regulators near power header (bottom left of back)
    place("U_REG_5V", 15, 115, front=False)
    place("U_REG_3V3", 25, 115, front=False)

    # Power header (back side, near bottom)
    place("J_POWER", 10, 120)

    board.Save(output_pcb)
    print(f"Placed components, saved to {output_pcb}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.kicad_pcb> [output.kicad_pcb]")
        sys.exit(1)

    input_pcb = sys.argv[1]
    output_pcb = sys.argv[2] if len(sys.argv) > 2 else None
    place_components(input_pcb, output_pcb)


if __name__ == "__main__":
    main()
