#!/usr/bin/env python3
"""Place components on KiCad PCB using positions from panel-layout.json.

Reads the .kicad_pcb generated by `ato build`, places through-hole components
at their faceplate positions, and groups SMD components near their connected
through-hole counterparts.

Components are looked up by their atopile_address property (not reference
designator), since atopile auto-assigns generic refs like R1, C1, etc.

Usage:
    python place_components.py <input.kicad_pcb> [output.kicad_pcb]

Requires: KiCad's pcbnew Python module (available in KiCad installation or Docker).
"""

import json
import os
import sys

LAYOUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "panel-layout.json")


def load_layout():
    with open(LAYOUT_PATH) as f:
        return json.load(f)


def place_components(input_pcb, output_pcb=None):
    """Place components using pcbnew API.

    Requires KiCad's Python environment:
        DYLD_FRAMEWORK_PATH=...KiCad.app/Contents/Frameworks
        PYTHONPATH=...KiCad.app/.../site-packages
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python (see Makefile hw-place).")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    layout = load_layout()
    panel = layout["panel"]

    board = pcbnew.LoadBoard(input_pcb)

    # Set board outline
    w_mm = panel["width_mm"]
    h_mm = panel["height_mm"]
    edge_layer = board.GetLayerID("Edge.Cuts")

    seg_coords = [
        (0, 0, w_mm, 0),
        (w_mm, 0, w_mm, h_mm),
        (w_mm, h_mm, 0, h_mm),
        (0, h_mm, 0, 0),
    ]
    for x1, y1, x2, y2 in seg_coords:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Build lookup from atopile_address to footprint
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp

    placed = 0
    placed_addrs = set()
    warnings = []

    def place(addr, x_mm, y_mm, front=True):
        nonlocal placed
        if addr not in addr_map:
            warnings.append(addr)
            return
        fp = addr_map[addr]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x_mm), pcbnew.FromMM(y_mm)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        placed += 1
        placed_addrs.add(addr)

    # --- Through-hole components (front side, from panel layout) ---

    # Jacks — utility
    utility_addr_map = {
        "clk_in": "jacks.j_clk_in",
        "clk_out": "jacks.j_clk_out",
        "rst_in": "jacks.j_rst_in",
        "rst_out": "jacks.j_rst_out",
        "midi_in": "midi.jack_in",
        "midi_out": "midi.jack_out",
    }
    for jack in layout["jacks"]["utility"]:
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place(addr, jack["x_mm"], jack["y_mm"])

    # Jacks — output (gate1..4, pitch1..4, vel1..4, mod1..4)
    for jack in layout["jacks"]["output"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"])

    # Jacks — CV input
    for jack in layout["jacks"]["cv_input"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"])

    # Buttons — track (t1..t4)
    for btn in layout["buttons"]["track"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons — subtrack (gate, pitch, vel, mod)
    for btn in layout["buttons"]["subtrack"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Button — pat (single item)
    pat = layout["buttons"].get("pat")
    if pat:
        place(f"buttons.btn_{pat['id']}", pat["x_mm"], pat["y_mm"])

    # Buttons — feature (mute, route, drift, trns/xpose, var)
    feature_addr_map = {"trns": "xpose"}  # layout uses "trns", ato uses "xpose"
    for btn in layout["buttons"]["feature"]:
        ato_id = feature_addr_map.get(btn["id"], btn["id"])
        addr = f"buttons.btn_{ato_id}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons — step (step1..step16)
    for btn in layout["buttons"]["step"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons — transport (play, reset, settings)
    for btn in layout["buttons"].get("transport", []):
        if btn["id"] == "settings":
            # Settings button is in ButtonScanner (SR5)
            addr = "buttons.btn_settings"
        else:
            addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Encoders
    for enc in layout["encoders"]:
        place(enc["id"], enc["x_mm"], enc["y_mm"])

    # --- SMD components (back side) ---
    # Group unplaced SMD parts by their module prefix, then lay them out
    # in functional zones on the back of the board.
    jack_zone_x = layout["jacks"]["output"][0]["x_mm"]
    step_x = layout["buttons"]["step"][0]["x_mm"]
    center_x = panel["width_mm"] / 2

    # Pico module centered
    place("mcu.pico", center_x, 40, front=False)

    # Power header near bottom
    place("power.header", 10, 120)

    # LCD header near LCD cutout (front side, below the display)
    lcd = layout.get("lcd_cutout", {})
    lcd_x = lcd.get("center_x_mm", center_x)
    lcd_bottom = lcd.get("center_y_mm", 37) + lcd.get("height_mm", 49) / 2 + 5
    place("display.header", lcd_x, lcd_bottom)

    # Zone assignments: module prefix -> (center_x, start_y) on back side
    zones = {
        "dac.":     (jack_zone_x - 10, 55),   # DAC near output jacks
        "power.":   (15, 108),                  # Power near bottom-left
        "buttons.": (step_x + 35, 75),          # Button support near buttons
        "leds.":    (step_x + 35, 110),          # LED drivers near buttons
        "midi.":    (160, 35),                   # MIDI near MIDI jacks
        "jacks.":   (jack_zone_x + 10, 100),    # Jack protection near jacks
        "display.": (center_x, 25),              # Display support near LCD
        "mcu.":     (center_x, 50),              # MCU support near Pico
    }
    # Top-level components (encoders' pullups/caps)
    top_level_zone = (15, 65)

    zone_groups = {prefix: [] for prefix in zones}
    zone_groups["_top"] = []

    for addr in addr_map:
        if addr in placed_addrs:
            continue
        assigned = False
        for prefix in zones:
            if addr.startswith(prefix):
                zone_groups[prefix].append(addr)
                assigned = True
                break
        if not assigned:
            zone_groups["_top"].append(addr)

    # Place each group in a grid within its zone
    grid_spacing = 4.0  # mm between SMD components
    cols_per_row = 8

    for prefix, addrs in zone_groups.items():
        if not addrs:
            continue
        if prefix == "_top":
            cx, cy = top_level_zone
        else:
            cx, cy = zones[prefix]

        for i, addr in enumerate(sorted(addrs)):
            col = i % cols_per_row
            row = i // cols_per_row
            x = cx + (col - cols_per_row / 2) * grid_spacing
            y = cy + row * grid_spacing
            # Clamp to board bounds
            x = max(3, min(w_mm - 3, x))
            y = max(3, min(h_mm - 3, y))
            place(addr, x, y, front=False)

    # Print summary
    print(f"  Placed {placed}/{len(addr_map)} components")
    if warnings:
        print(f"  {len(warnings)} addresses not found:")
        for w in warnings:
            print(f"    - {w}")

    board.Save(output_pcb)
    print(f"  Saved to {output_pcb}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.kicad_pcb> [output.kicad_pcb]")
        sys.exit(1)

    input_pcb = sys.argv[1]
    output_pcb = sys.argv[2] if len(sys.argv) > 2 else None
    place_components(input_pcb, output_pcb)


if __name__ == "__main__":
    main()
