#!/usr/bin/env python3
"""Convert board STEP files to glTF (.glb) for the web 3D assembly viewer.

Reads STEP files from hardware/boards/build/3d/ (generated by export_3d_assembly.py)
and converts them to binary glTF (.glb) files in web/public/models/.

Preserves STEP product/solid names as glTF node names so the web viewer can
classify materials by component type (e.g. J1_TN → jack threaded nut).

Requires one of:
  - OCP (cadquery/build123d): pip install cadquery  (recommended, preserves names)
  - trimesh + cascadio:       pip install trimesh cascadio  (fallback, no names)

Usage:
    python3 export_gltf.py [--input-dir DIR] [--output-dir DIR]
"""

import argparse
import importlib
import json
import struct
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BOARDS_DIR = SCRIPT_DIR.parent.parent
REPO_ROOT = BOARDS_DIR.parent.parent
DEFAULT_INPUT = BOARDS_DIR / "build" / "3d"
DEFAULT_OUTPUT = REPO_ROOT / "web" / "public" / "models"

BOARDS = ["faceplate", "control", "main"]


def convert_with_ocp(step_path: Path, glb_path: Path) -> bool:
    """Convert using OCP's XDE API, preserving STEP product/solid names as glTF nodes.

    Uses the Extended Data Framework to read the STEP assembly tree with labels,
    tessellates each shape, and builds a glTF scene graph that mirrors the hierarchy.
    """
    from OCP.STEPCAFControl import STEPCAFControl_Reader
    from OCP.TDocStd import TDocStd_Document
    from OCP.XCAFDoc import XCAFDoc_DocumentTool, XCAFDoc_ShapeTool, XCAFDoc_Location
    from OCP.TDF import TDF_LabelSequence, TDF_Label
    from OCP.TDataStd import TDataStd_Name
    from OCP.BRep import BRep_Tool
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_FACE
    from OCP.BRepMesh import BRepMesh_IncrementalMesh
    from OCP.TopLoc import TopLoc_Location
    from OCP.IFSelect import IFSelect_RetDone
    import numpy as np

    # Read STEP with XDE to preserve assembly structure + names
    doc = TDocStd_Document("XmlOcaf")
    reader = STEPCAFControl_Reader()
    reader.SetNameMode(True)
    reader.SetColorMode(True)

    status = reader.ReadFile(str(step_path))
    if status != IFSelect_RetDone:
        print(f"  ERROR: Failed to read {step_path.name}")
        return False

    reader.Transfer(doc)

    shape_tool = XCAFDoc_DocumentTool.ShapeTool(doc.Main())

    def get_label_name(label: TDF_Label) -> str:
        """Get the name string from a TDF label."""
        name_attr = TDataStd_Name()
        if label.FindAttribute(TDataStd_Name.GetID(), name_attr):
            return name_attr.Get().ToExtString()
        return ""

    def tessellate_shape(shape, deflection=0.5):
        """Tessellate a shape and return (vertices, faces) arrays."""
        mesh_maker = BRepMesh_IncrementalMesh(shape, deflection)
        mesh_maker.Perform()

        verts = []
        tris = []
        offset = 0

        explorer = TopExp_Explorer(shape, TopAbs_FACE)
        while explorer.More():
            face = explorer.Current()
            loc = TopLoc_Location()
            triangulation = BRep_Tool.Triangulation(face, loc)

            if triangulation is not None:
                trsf = loc.Transformation()
                n_nodes = triangulation.NbNodes()
                n_tris = triangulation.NbTriangles()

                for i in range(1, n_nodes + 1):
                    pt = triangulation.Node(i)
                    # Apply location transform
                    pt = pt.Transformed(trsf)
                    verts.append([pt.X(), pt.Y(), pt.Z()])

                for i in range(1, n_tris + 1):
                    tri = triangulation.Triangle(i)
                    n1, n2, n3 = tri.Get()
                    tris.append([n1 - 1 + offset, n2 - 1 + offset, n3 - 1 + offset])

                offset += n_nodes

            explorer.Next()

        if not verts:
            return None, None
        return np.array(verts, dtype=np.float32), np.array(tris, dtype=np.uint32)

    # Collect named meshes from the assembly tree
    meshes = []  # [(name, vertices, faces)]

    def collect_shapes(label: TDF_Label, parent_name: str = ""):
        """Recursively collect shapes with their names from the XDE tree."""
        name = get_label_name(label)
        full_name = f"{parent_name}_{name}" if parent_name and name else (name or parent_name)

        if shape_tool.IsSimpleShape(label):
            shape = shape_tool.GetShape(label)
            if shape is not None and not shape.IsNull():
                verts, faces = tessellate_shape(shape)
                if verts is not None and len(verts) > 0:
                    meshes.append((full_name or f"shape_{len(meshes)}", verts, faces))

        # Recurse into sub-labels (components/children)
        sub_labels = TDF_LabelSequence()
        if shape_tool.IsAssembly(label):
            shape_tool.GetComponents(label, sub_labels)
            for i in range(1, sub_labels.Length() + 1):
                comp_label = sub_labels.Value(i)
                # Get the referred shape label for assemblies
                ref_label = TDF_Label()
                if shape_tool.GetReferredShape(comp_label, ref_label):
                    comp_name = get_label_name(comp_label)
                    ref_name = get_label_name(ref_label)
                    use_name = comp_name or ref_name
                    collect_shapes(ref_label, use_name)
                else:
                    collect_shapes(comp_label, full_name)

        sub_shapes = TDF_LabelSequence()
        shape_tool.GetSubShapes(label, sub_shapes)
        for i in range(1, sub_shapes.Length() + 1):
            collect_shapes(sub_shapes.Value(i), full_name)

    # Start from free shapes (top-level assembly roots)
    free_shapes = TDF_LabelSequence()
    shape_tool.GetFreeShapes(free_shapes)
    for i in range(1, free_shapes.Length() + 1):
        collect_shapes(free_shapes.Value(i))

    # If XDE tree didn't yield named meshes, fall back to flat tessellation
    if not meshes:
        from OCP.STEPControl import STEPControl_Reader as FlatReader
        flat_reader = FlatReader()
        flat_reader.ReadFile(str(step_path))
        flat_reader.TransferRoots()
        shape = flat_reader.OneShape()
        verts, faces = tessellate_shape(shape)
        if verts is not None:
            meshes.append(("board", verts, faces))

    if not meshes:
        print(f"  WARNING: No geometry extracted from {step_path.name}")
        return False

    # Build glTF with named nodes
    _write_glb(glb_path, meshes)
    return glb_path.exists()


def _write_glb(glb_path: Path, meshes: list) -> None:
    """Write a binary glTF (.glb) file with named mesh nodes.

    Each (name, vertices, faces) tuple becomes a named node in the scene.
    """
    # Build buffer data
    buffer_data = bytearray()
    accessors = []
    buffer_views = []
    gltf_meshes = []
    nodes = []

    for i, (name, verts, faces) in enumerate(meshes):
        # Vertex data
        vert_bytes = verts.astype("<f4").tobytes()
        vert_offset = len(buffer_data)
        buffer_data.extend(vert_bytes)
        # Pad to 4-byte boundary
        while len(buffer_data) % 4:
            buffer_data.append(0)

        # Index data
        idx_bytes = faces.astype("<I").tobytes()
        idx_offset = len(buffer_data)
        buffer_data.extend(idx_bytes)
        while len(buffer_data) % 4:
            buffer_data.append(0)

        # Buffer views
        vert_bv = len(buffer_views)
        buffer_views.append({
            "buffer": 0,
            "byteOffset": vert_offset,
            "byteLength": len(vert_bytes),
            "target": 34962,  # ARRAY_BUFFER
        })
        idx_bv = len(buffer_views)
        buffer_views.append({
            "buffer": 0,
            "byteOffset": idx_offset,
            "byteLength": len(idx_bytes),
            "target": 34963,  # ELEMENT_ARRAY_BUFFER
        })

        # Accessors
        v_min = verts.min(axis=0).tolist()
        v_max = verts.max(axis=0).tolist()
        vert_acc = len(accessors)
        accessors.append({
            "bufferView": vert_bv,
            "componentType": 5126,  # FLOAT
            "count": len(verts),
            "type": "VEC3",
            "min": v_min,
            "max": v_max,
        })
        idx_acc = len(accessors)
        accessors.append({
            "bufferView": idx_bv,
            "componentType": 5125,  # UNSIGNED_INT
            "count": len(faces) * 3,
            "type": "SCALAR",
            "min": [int(faces.min())],
            "max": [int(faces.max())],
        })

        # Mesh
        gltf_meshes.append({
            "name": name,
            "primitives": [{
                "attributes": {"POSITION": vert_acc},
                "indices": idx_acc,
                "mode": 4,  # TRIANGLES
            }],
        })

        # Node
        nodes.append({
            "name": name,
            "mesh": i,
        })

    # Scene
    gltf = {
        "asset": {"version": "2.0", "generator": "requencer-export"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(nodes)))}],
        "nodes": nodes,
        "meshes": gltf_meshes,
        "accessors": accessors,
        "bufferViews": buffer_views,
        "buffers": [{"byteLength": len(buffer_data)}],
    }

    json_str = json.dumps(gltf, separators=(",", ":"))
    json_bytes = json_str.encode("utf-8")
    # Pad JSON to 4-byte boundary with spaces
    while len(json_bytes) % 4:
        json_bytes += b" "

    # GLB header: magic + version + length
    total_length = 12 + 8 + len(json_bytes) + 8 + len(buffer_data)

    with open(glb_path, "wb") as f:
        # Header
        f.write(struct.pack("<III", 0x46546C67, 2, total_length))  # glTF magic, version 2
        # JSON chunk
        f.write(struct.pack("<II", len(json_bytes), 0x4E4F534A))  # JSON chunk type
        f.write(json_bytes)
        # Binary chunk
        f.write(struct.pack("<II", len(buffer_data), 0x004E4942))  # BIN chunk type
        f.write(buffer_data)


def convert_with_trimesh(step_path: Path, glb_path: Path) -> bool:
    """Fallback: convert using trimesh (no name preservation)."""
    import trimesh

    mesh = trimesh.load(str(step_path))
    mesh.export(str(glb_path), file_type="glb")
    return glb_path.exists()


# Backends in preference order (OCP preserves names, trimesh is fallback)
BACKENDS = [
    ("OCP", convert_with_ocp, ["OCP"]),
    ("trimesh", convert_with_trimesh, ["trimesh"]),
]


def find_backend():
    """Find the first available conversion backend."""
    for name, fn, modules in BACKENDS:
        try:
            for mod in modules:
                importlib.import_module(mod)
            return name, fn
        except ImportError:
            continue
    return None, None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input-dir", "-i", type=Path, default=DEFAULT_INPUT,
                        help="Directory containing board STEP files")
    parser.add_argument("--output-dir", "-o", type=Path, default=DEFAULT_OUTPUT,
                        help="Output directory for glTF files")
    args = parser.parse_args()

    backend_name, convert_fn = find_backend()
    if not convert_fn:
        print("ERROR: No STEP->glTF conversion backend available.")
        print("Install one of:")
        print("  pip install cadquery          (recommended, preserves names)")
        print("  pip install trimesh cascadio  (lightweight, no names)")
        sys.exit(1)

    preserves_names = backend_name == "OCP"
    print(f"Using backend: {backend_name}" +
          (" (preserves STEP names)" if preserves_names else " (names not preserved)"))

    input_dir = args.input_dir
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_dir.exists():
        print(f"ERROR: Input directory not found: {input_dir}")
        print("Run 'make hw-3d' first to generate STEP files.")
        sys.exit(1)

    # Copy stack-up metadata to output dir if it exists
    metadata_src = input_dir / "stack-up.json"
    if metadata_src.exists():
        import shutil
        shutil.copy2(metadata_src, output_dir / "stack-up.json")
        print(f"  Copied stack-up.json to {output_dir}")

    success = 0
    for board in BOARDS:
        step_path = input_dir / f"{board}.step"
        glb_path = output_dir / f"{board}.glb"

        if not step_path.exists():
            print(f"  SKIP: {step_path.name} not found")
            continue

        print(f"  Converting {step_path.name} -> {glb_path.name} ...", end=" ", flush=True)
        try:
            if convert_fn(step_path, glb_path):
                size_mb = glb_path.stat().st_size / (1024 * 1024)
                print(f"OK ({size_mb:.1f} MB)")
                success += 1
            else:
                print("FAILED")
        except Exception as e:
            print(f"ERROR: {e}")

    print(f"\nConverted {success}/{len(BOARDS)} boards to glTF")
    print(f"Output: {output_dir}/")


if __name__ == "__main__":
    main()
