#!/usr/bin/env python3
"""Convert board STEP files to glTF (.glb) for the web 3D assembly viewer.

Reads STEP files from hardware/boards/build/3d/ (generated by export_3d_assembly.py)
and converts them to binary glTF (.glb) files in web/public/models/.

Requires one of:
  - cadquery:        pip install cadquery
  - pythonocc-core:  conda install -c conda-forge pythonocc-core
  - trimesh + OCP:   pip install trimesh

Usage:
    python3 export_gltf.py [--input-dir DIR] [--output-dir DIR]

Typically run via: make hw-export-gltf
"""

import argparse
import importlib
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent
DEFAULT_INPUT = SCRIPT_DIR.parent / "build" / "3d"
DEFAULT_OUTPUT = REPO_ROOT / "web" / "public" / "models"

BOARDS = ["faceplate", "control", "main"]


def convert_with_cadquery(step_path: Path, glb_path: Path) -> bool:
    """Convert using cadquery's built-in STEP importer and glTF exporter."""
    import cadquery as cq
    from cadquery import exporters

    shape = cq.importers.importStep(str(step_path))
    exporters.export(shape, str(glb_path), exportType="GLTF")
    return glb_path.exists()


def convert_with_trimesh(step_path: Path, glb_path: Path) -> bool:
    """Convert using trimesh (requires OCP or cascadio for STEP import)."""
    import trimesh

    mesh = trimesh.load(str(step_path))
    mesh.export(str(glb_path), file_type="glb")
    return glb_path.exists()


def convert_with_pythonocc(step_path: Path, glb_path: Path) -> bool:
    """Convert using pythonocc-core for STEP reading + trimesh for glTF export."""
    from OCP.STEPControl import STEPControl_Reader
    from OCP.IFSelect import IFSelect_RetDone
    from OCP.BRep import BRep_Tool
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_FACE
    from OCP.BRepMesh import BRepMesh_IncrementalMesh
    import numpy as np
    import trimesh

    reader = STEPControl_Reader()
    status = reader.ReadFile(str(step_path))
    if status != IFSelect_RetDone:
        print(f"  ERROR: Failed to read {step_path.name}")
        return False

    reader.TransferRoots()
    shape = reader.OneShape()

    # Tessellate
    mesh_maker = BRepMesh_IncrementalMesh(shape, 0.5)  # 0.5mm deflection
    mesh_maker.Perform()

    # Extract triangles
    vertices = []
    faces = []
    offset = 0

    explorer = TopExp_Explorer(shape, TopAbs_FACE)
    while explorer.More():
        face = explorer.Current()
        location = face.Location()
        triangulation = BRep_Tool.Triangulation(face, location)

        if triangulation is not None:
            n_nodes = triangulation.NbNodes()
            n_tris = triangulation.NbTriangles()

            for i in range(1, n_nodes + 1):
                pt = triangulation.Node(i)
                vertices.append([pt.X(), pt.Y(), pt.Z()])

            for i in range(1, n_tris + 1):
                tri = triangulation.Triangle(i)
                n1, n2, n3 = tri.Get()
                faces.append([n1 - 1 + offset, n2 - 1 + offset, n3 - 1 + offset])

            offset += n_nodes

        explorer.Next()

    if not vertices:
        print(f"  WARNING: No geometry extracted from {step_path.name}")
        return False

    mesh = trimesh.Trimesh(
        vertices=np.array(vertices),
        faces=np.array(faces),
    )
    mesh.export(str(glb_path), file_type="glb")
    return glb_path.exists()


# Backends in preference order
BACKENDS = [
    ("cadquery", convert_with_cadquery),
    ("trimesh", convert_with_trimesh),
    ("pythonocc", convert_with_pythonocc),
]


def find_backend():
    """Find the first available conversion backend."""
    for name, fn in BACKENDS:
        try:
            if name == "cadquery":
                importlib.import_module("cadquery")
            elif name == "trimesh":
                importlib.import_module("trimesh")
            elif name == "pythonocc":
                importlib.import_module("OCP")
                importlib.import_module("trimesh")
            return name, fn
        except ImportError:
            continue
    return None, None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input-dir", "-i", type=Path, default=DEFAULT_INPUT,
                        help="Directory containing board STEP files")
    parser.add_argument("--output-dir", "-o", type=Path, default=DEFAULT_OUTPUT,
                        help="Output directory for glTF files")
    args = parser.parse_args()

    backend_name, convert_fn = find_backend()
    if not convert_fn:
        print("ERROR: No STEP→glTF conversion backend available.")
        print("Install one of:")
        print("  pip install cadquery          (recommended)")
        print("  pip install trimesh cascadio  (lightweight)")
        print("  conda install pythonocc-core  (heavy)")
        sys.exit(1)

    print(f"Using backend: {backend_name}")

    input_dir = args.input_dir
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_dir.exists():
        print(f"ERROR: Input directory not found: {input_dir}")
        print("Run 'make hw-3d-export' first to generate STEP files.")
        sys.exit(1)

    success = 0
    for board in BOARDS:
        step_path = input_dir / f"{board}.step"
        glb_path = output_dir / f"{board}.glb"

        if not step_path.exists():
            print(f"  SKIP: {step_path.name} not found")
            continue

        print(f"  Converting {step_path.name} → {glb_path.name} ...", end=" ", flush=True)
        try:
            if convert_fn(step_path, glb_path):
                size_mb = glb_path.stat().st_size / (1024 * 1024)
                print(f"OK ({size_mb:.1f} MB)")
                success += 1
            else:
                print("FAILED")
        except Exception as e:
            print(f"ERROR: {e}")

    print(f"\nConverted {success}/{len(BOARDS)} boards to glTF")
    print(f"Output: {output_dir}/")


if __name__ == "__main__":
    main()
