#!/usr/bin/env python3
"""Place components on KiCad PCB using positions from panel-layout.json.

Reads the .kicad_pcb generated by `ato build`, places through-hole components
at their faceplate positions, and groups SMD components near their connected
through-hole counterparts.

Components are looked up by their atopile_address property (not reference
designator), since atopile auto-assigns generic refs like R1, C1, etc.

Supports multi-board builds:
  - Control board (default): Full panel placement with layout + zones.
  - Main board (--board main): Compact grid placement, no panel layout.
    Detected via --board flag or "main" in PCB filename.

Usage:
    python place_components.py [--board control|main] <input.kicad_pcb> [output.kicad_pcb]

Requires: KiCad's pcbnew Python module (available in KiCad installation or Docker).
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict

LAYOUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "..", "web", "src", "panel-layout.json")
COMPONENT_MAP_PATH = os.path.join(os.path.dirname(__file__), "..", "component-map.json")


class CollisionTracker:
    """Track placed component footprints and detect collisions.

    Every placed component is registered as a rectangle on a side (F/B).
    THT components occupy BOTH sides (pins penetrate the board).

    Collision rules:
      - SMD vs SMD: collide only if same side
      - THT vs anything: collide on both sides
      - All checks use actual footprint bounding boxes + clearance margin
    """

    def __init__(self, board_w, board_h, clearance=0.5):
        self.board_w = board_w
        self.board_h = board_h
        self.clearance = clearance
        # Each entry: (x1, y1, x2, y2, side, label)
        # side is "F", "B", or "both" (for THT)
        self._rects = []

    def register(self, cx, cy, w, h, side, is_tht, label=""):
        """Register a placed component. cx/cy is center, w/h is full extent."""
        margin = self.clearance
        x1 = cx - w / 2 - margin
        y1 = cy - h / 2 - margin
        x2 = cx + w / 2 + margin
        y2 = cy + h / 2 + margin
        effective_side = "both" if is_tht else side
        self._rects.append((x1, y1, x2, y2, effective_side, label))

    def register_bbox(self, x1, y1, x2, y2, side, is_tht, label=""):
        """Register using actual bounding box coords (not center+dims)."""
        margin = self.clearance
        effective_side = "both" if is_tht else side
        self._rects.append((x1 - margin, y1 - margin, x2 + margin, y2 + margin,
                            effective_side, label))

    def register_zone(self, x1, y1, x2, y2, side, label="zone"):
        """Register a static exclusion zone (e.g. LCD area)."""
        self._rects.append((x1, y1, x2, y2, side, label))

    def collides(self, cx, cy, w, h, side, is_tht=False):
        """Check if placing a component at (cx, cy) would collide."""
        hx = w / 2
        hy = h / 2
        ax1, ay1 = cx - hx, cy - hy
        ax2, ay2 = cx + hx, cy + hy
        check_side = "both" if is_tht else side

        for bx1, by1, bx2, by2, bside, _ in self._rects:
            # Determine if these two items can collide based on sides
            if not self._sides_conflict(check_side, bside):
                continue
            # AABB overlap test
            if ax1 < bx2 and ax2 > bx1 and ay1 < by2 and ay2 > by1:
                return True
        return False

    def in_bounds(self, cx, cy, w, h):
        """Check if a component body fits within board edges."""
        hx, hy = w / 2, h / 2
        return (cx - hx >= 0 and cy - hy >= 0 and
                cx + hx <= self.board_w and cy + hy <= self.board_h)

    def find_free(self, cx, cy, w, h, side, is_tht, zone_bounds=None, step=1.0):
        """Find the nearest collision-free position starting from (cx, cy).

        Uses expanding ring search: tries positions at increasing distance.
        zone_bounds: (zx, zy, zw, zh) constrains the search area.
        If no free spot exists in zone, falls back to searching entire board.
        Returns (x, y) of first free position, or (cx, cy) if nothing found.
        """
        def _ring_search(min_x, min_y, max_x, max_y, max_rings):
            best = None
            best_dist = float('inf')
            for ring in range(1, max_rings + 1):
                d = ring * step
                candidates = []
                steps_per_side = ring
                for i in range(-steps_per_side, steps_per_side + 1):
                    candidates.append((cx + d, cy + i * step))
                    candidates.append((cx - d, cy + i * step))
                    candidates.append((cx + i * step, cy + d))
                    candidates.append((cx + i * step, cy - d))

                for tx, ty in candidates:
                    if tx < min_x or tx > max_x or ty < min_y or ty > max_y:
                        continue
                    if not self.collides(tx, ty, w, h, side, is_tht):
                        dist = abs(tx - cx) + abs(ty - cy)
                        if dist < best_dist:
                            best = (tx, ty)
                            best_dist = dist

                if best is not None:
                    return best
            return None

        # Quick check: is the original position free?
        if (not self.collides(cx, cy, w, h, side, is_tht) and
                self.in_bounds(cx, cy, w, h)):
            return cx, cy

        max_radius = max(self.board_w, self.board_h)
        max_rings = int(max_radius / step) + 1

        # Search within zone bounds first
        if zone_bounds:
            zx, zy, zw, zh = zone_bounds
            min_x, min_y = zx + w / 2, zy + h / 2
            max_x, max_y = zx + zw - w / 2, zy + zh - h / 2
            result = _ring_search(min_x, min_y, max_x, max_y, max_rings)
            if result:
                return result

        # Fallback: search entire board
        min_x, min_y = w / 2, h / 2
        max_x = self.board_w - w / 2
        max_y = self.board_h - h / 2
        result = _ring_search(min_x, min_y, max_x, max_y, max_rings)
        if result:
            return result

        # Last resort: return original position (will overlap)
        return cx, cy

    def find_largest_free_rects(self, side, resolution=2.0, count=5, edge_margin=5.0):
        """Find the largest empty rectangles on the given side.

        Scans the board on a grid, builds a height map, and uses the
        'largest rectangle in histogram' algorithm to find maximal empty rects.
        edge_margin keeps components away from board edges for routing access.
        Returns up to `count` non-overlapping rectangles as (x, y, w, h) tuples.
        """
        cols = int(self.board_w / resolution)
        rows = int(self.board_h / resolution)

        # Build occupancy grid — True means blocked
        grid = [[False] * cols for _ in range(rows)]
        for r in range(rows):
            for c in range(cols):
                x = (c + 0.5) * resolution
                y = (r + 0.5) * resolution
                # Block board edges (routing needs access from all sides)
                if (x < edge_margin or x > self.board_w - edge_margin or
                        y < edge_margin or y > self.board_h - edge_margin):
                    grid[r][c] = True
                elif self.collides(x, y, resolution * 0.9, resolution * 0.9, side):
                    grid[r][c] = True

        results = []
        for _ in range(count):
            # Build height array (consecutive free cells above each position)
            heights = [0] * cols
            best_area = 0
            best = None

            for r in range(rows):
                for c in range(cols):
                    heights[c] = 0 if grid[r][c] else heights[c] + 1

                # Largest rectangle in this histogram row
                stack = []
                for c in range(cols + 1):
                    h = heights[c] if c < cols else 0
                    while stack and heights[stack[-1]] > h:
                        height = heights[stack.pop()]
                        width = c if not stack else c - stack[-1] - 1
                        area = height * width
                        if area > best_area:
                            best_area = area
                            x0 = (stack[-1] + 1 if stack else 0) * resolution
                            y0 = (r - height + 1) * resolution
                            best = (x0, y0, width * resolution, height * resolution)
                    stack.append(c)

            if not best or best_area < 4:  # minimum 4 grid cells
                break
            results.append(best)

            # Mark this rect as occupied so we find the next largest
            rx, ry, rw, rh = best
            for r in range(rows):
                for c in range(cols):
                    x = (c + 0.5) * resolution
                    y = (r + 0.5) * resolution
                    if rx <= x <= rx + rw and ry <= y <= ry + rh:
                        grid[r][c] = True

        return results

    @staticmethod
    def _sides_conflict(side_a, side_b):
        """Return True if two items on these sides can physically collide."""
        if side_a == "both" or side_b == "both":
            return True
        return side_a == side_b

    def get_footprint_dims(self, fp, pcbnew):
        """Get footprint body width and height in mm from KiCad footprint."""
        bbox = fp.GetBoundingBox(False, False)  # exclude text
        w = pcbnew.ToMM(bbox.GetWidth())
        h = pcbnew.ToMM(bbox.GetHeight())
        return max(w, 1.0), max(h, 1.0)  # minimum 1mm

    def is_tht(self, fp, pcbnew):
        """Check if footprint has any through-hole pads."""
        return any(
            pad.GetAttribute() == pcbnew.PAD_ATTRIB_PTH for pad in fp.Pads()
        )

    def get_ref_text_bbox(self, fp, pcbnew):
        """Get reference designator text bounding box in board coordinates.

        Returns (x1, y1, x2, y2) in mm, or None if ref text is hidden/missing.
        """
        ref = fp.Reference()
        if not ref or not ref.IsVisible():
            return None

        text_str = ref.GetShownText(False)
        if not text_str:
            return None

        # Get text bounding box from KiCad (includes font size and rotation)
        text_bbox = ref.GetBoundingBox()
        x1 = pcbnew.ToMM(text_bbox.GetLeft())
        y1 = pcbnew.ToMM(text_bbox.GetTop())
        x2 = pcbnew.ToMM(text_bbox.GetRight())
        y2 = pcbnew.ToMM(text_bbox.GetBottom())

        # Ensure minimum dimensions (text can be tiny)
        if x2 - x1 < 0.5 or y2 - y1 < 0.3:
            return None

        return (x1, y1, x2, y2)

    def register_label(self, fp, pcbnew, side):
        """Register reference designator text as a collision rect with small clearance."""
        bbox = self.get_ref_text_bbox(fp, pcbnew)
        if bbox is None:
            return
        x1, y1, x2, y2 = bbox
        label_clearance = 0.3
        self._rects.append((
            x1 - label_clearance, y1 - label_clearance,
            x2 + label_clearance, y2 + label_clearance,
            side, f"label:{fp.GetReference()}"
        ))

    @property
    def count(self):
        return len(self._rects)

    def overlap_report(self):
        """Return list of all current overlaps between actual component bodies.

        Registered rects include clearance margins. Shrink by clearance before
        comparing to report real physical overlaps, not just clearance violations.
        """
        overlaps = []
        c = self.clearance
        for i in range(len(self._rects)):
            ax1, ay1, ax2, ay2, aside, alabel = self._rects[i]
            # Shrink to actual body
            ax1, ay1, ax2, ay2 = ax1 + c, ay1 + c, ax2 - c, ay2 - c
            for j in range(i + 1, len(self._rects)):
                bx1, by1, bx2, by2, bside, blabel = self._rects[j]
                if not self._sides_conflict(aside, bside):
                    continue
                bx1, by1, bx2, by2 = bx1 + c, by1 + c, bx2 - c, by2 - c
                dx = min(ax2, bx2) - max(ax1, bx1)
                dy = min(ay2, by2) - max(ay1, by1)
                if dx > 0 and dy > 0:
                    overlaps.append((alabel, blabel, aside, bside, dx * dy))
        return overlaps


def load_layout():
    with open(LAYOUT_PATH) as f:
        return json.load(f)


def load_component_map():
    with open(COMPONENT_MAP_PATH) as f:
        return json.load(f)


def identify_power_nets(board):
    """Return set of net names that are power/ground (useless for placement affinity).

    Uses two heuristics:
      1. Name patterns: gnd, vcc, vdd, 3v3, 5v, 12v, avdd, etc.
      2. High fanout: any net connected to >15 pads is likely power.
    """
    power_pattern = re.compile(
        r"(^|\W)(gnd|vcc|vdd|vss|avdd|avss|dvdd|dvss"
        r"|v5v|v3v3|v12p|v12n|\+12v|\-12v|\+5v|\+3\.3v"
        r"|hv|vsys|vbus|vref|agnd|dgnd|pgnd)"
        r"($|\W)",
        re.IGNORECASE,
    )
    power_nets = set()

    # Pattern-based detection
    netinfo = board.GetNetInfo()
    for net in netinfo.NetsByName():
        name = str(net)
        if power_pattern.search(name):
            power_nets.add(name)

    # Fanout-based detection: count pads per net
    pad_count = defaultdict(int)
    for fp in board.GetFootprints():
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name:
                pad_count[net_name] += 1
    for net_name, count in pad_count.items():
        if count > 15:
            power_nets.add(net_name)

    return power_nets


def build_connectivity_graph(board, addrs, addr_map, power_nets):
    """Build adjacency graph: addr -> {neighbor_addr: shared_net_count}.

    Two SMD components are connected if they share at least one non-power net.
    """
    # Map net_name -> list of addrs that have pads on that net
    net_to_addrs = defaultdict(set)
    for addr in addrs:
        fp = addr_map[addr]
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name and net_name not in power_nets:
                net_to_addrs[net_name].add(addr)

    # Build adjacency from shared nets
    graph = defaultdict(lambda: defaultdict(int))
    for net_name, connected_addrs in net_to_addrs.items():
        addr_list = list(connected_addrs)
        for i in range(len(addr_list)):
            for j in range(i + 1, len(addr_list)):
                graph[addr_list[i]][addr_list[j]] += 1
                graph[addr_list[j]][addr_list[i]] += 1

    return graph


def connectivity_sort(addrs, graph):
    """Order components so electrically-connected ones are adjacent.

    Greedy BFS: start from the most-connected node, always visit the
    unvisited neighbor with the strongest connection. Handles disconnected
    subgraphs -- isolated components go at the end.
    """
    if not addrs:
        return []

    remaining = set(addrs)
    ordered = []

    while remaining:
        # Pick start node: most total connection weight among remaining
        start = max(
            remaining,
            key=lambda a: sum(graph[a].get(n, 0) for n in remaining) if a in graph else 0,
        )
        remaining.remove(start)
        ordered.append(start)

        # Greedy walk: always pick the strongest unvisited neighbor
        current = start
        while True:
            neighbors = {
                n: w for n, w in graph.get(current, {}).items() if n in remaining
            }
            if not neighbors:
                # No connected unvisited neighbors -- check if any remaining
                # node connects to ANY already-ordered node
                best = None
                best_w = 0
                for r in remaining:
                    for o in ordered:
                        w = graph.get(r, {}).get(o, 0)
                        if w > best_w:
                            best = r
                            best_w = w
                if best and best_w > 0:
                    remaining.remove(best)
                    ordered.append(best)
                    current = best
                    continue
                break
            best_neighbor = max(neighbors, key=neighbors.get)
            remaining.remove(best_neighbor)
            ordered.append(best_neighbor)
            current = best_neighbor

    return ordered


def size_sort(addrs, addr_map, pcbnew):
    """Sort component addresses by footprint bounding-box area, largest first."""
    def area(addr):
        fp = addr_map.get(addr)
        if not fp:
            return 0
        bbox = fp.GetBoundingBox(False, False)
        return pcbnew.ToMM(bbox.GetWidth()) * pcbnew.ToMM(bbox.GetHeight())
    return sorted(addrs, key=area, reverse=True)



def place_main_board(input_pcb, output_pcb=None):
    """Place components on the main board using compact grid layout.

    The main board has no panel-facing THT components (those are on the control
    board). It contains SMD ICs and passives plus THT board-to-board headers.
    All components are placed in a compact grid with connectivity-aware ordering
    and collision-free placement.
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python (see Makefile hw-place).")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    board = pcbnew.LoadBoard(input_pcb)

    # Enable 4 copper layers
    board.SetCopperLayerCount(4)

    # Build lookup from atopile_address to footprint
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp

    if not addr_map:
        print("  No components with atopile_address found.")
        board.Save(output_pcb)
        return

    # Classify components
    ic_pin_threshold = 5
    ics = []
    passives = []
    headers = []  # THT connectors

    for addr, fp in addr_map.items():
        pad_count = len(list(fp.Pads()))
        has_tht = any(
            pad.GetAttribute() == pcbnew.PAD_ATTRIB_PTH for pad in fp.Pads()
        )
        if has_tht:
            headers.append(addr)
        elif pad_count >= ic_pin_threshold:
            ics.append(addr)
        else:
            passives.append(addr)

    print(f"  Main board: {len(headers)} headers, {len(ics)} ICs, {len(passives)} passives")

    # Build connectivity graph for ordering
    power_nets = identify_power_nets(board)
    all_addrs = list(addr_map.keys())
    conn_graph = build_connectivity_graph(board, all_addrs, addr_map, power_nets)

    # Order by footprint area (largest first — big parts get first pick of positions)
    ics = size_sort(ics, addr_map, pcbnew)
    passives = size_sort(passives, addr_map, pcbnew)

    # Board dimensions: match control board so the two boards stack in a sandwich.
    # Control board PCB is 177.88 x 107.5mm (from component-map.json).
    board_w = 177.88
    board_h = 107.5
    margin = 3.0

    # Measure tallest header for zone sizing
    header_spacing = 18.0
    max_header_h = 0
    for addr in headers:
        fp = addr_map.get(addr)
        if fp:
            bbox = fp.GetBoundingBox(False, False)
            h = pcbnew.ToMM(bbox.GetHeight())
            max_header_h = max(max_header_h, h)
    header_zone_h = max(max_header_h + 4, 20.0)

    # Layout zones (generous spacing with full board area available)
    ic_spacing = 14.0
    ic_cols = max(1, int((board_w - 2 * margin) / ic_spacing))
    ic_rows_count = (len(ics) + ic_cols - 1) // ic_cols if ics else 0
    ic_start_y = margin + header_zone_h + 5
    passive_spacing = 6.0
    passive_start_y = ic_start_y + ic_rows_count * ic_spacing + 5
    p_cols = max(1, int((board_w - 2 * margin) / passive_spacing))
    passive_rows = (len(passives) + p_cols - 1) // p_cols if passives else 0

    # Set board outline
    edge_layer = board.GetLayerID("Edge.Cuts")
    for x1, y1, x2, y2 in [
        (0, 0, board_w, 0), (board_w, 0, board_w, board_h),
        (board_w, board_h, 0, board_h), (0, board_h, 0, 0),
    ]:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Initialize collision tracker
    tracker = CollisionTracker(board_w, board_h, clearance=0.5)
    placed = 0

    def place(addr, x, y, front=True):
        """Place component and register with collision tracker."""
        nonlocal placed
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        w, h = tracker.get_footprint_dims(fp, pcbnew)
        is_through = tracker.is_tht(fp, pcbnew)
        side = "F" if front else "B"
        tracker.register(x, y, w, h, side, is_through, label=addr)
        placed += 1

    def place_collision_free(addr, desired_x, desired_y, front, zone_bounds=None):
        """Place component at nearest collision-free position."""
        nonlocal placed
        if addr not in addr_map:
            return
        fp = addr_map[addr]
        w, h = tracker.get_footprint_dims(fp, pcbnew)
        is_through = tracker.is_tht(fp, pcbnew)
        side = "F" if front else "B"
        x, y = tracker.find_free(desired_x, desired_y, w, h, side, is_through,
                                  zone_bounds, step=0.5)
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        tracker.register(x, y, w, h, side, is_through, label=addr)
        placed += 1

    # Place THT components with explicit positions.
    # Board connectors align with control board back-side positions (x=25, x=40).
    # Power header near right edge (eurorack cable entry).
    # MCU module centered on board.
    tht_positions = {
        "connector.header_a": (25, 28, True),    # front, aligned with control board
        "connector.header_b": (40, 28, True),    # front, aligned with control board
        "power.header":       (165, 15, False),  # back side — accessible from behind in rack
        "mcu.pga":            (90, 28, False),    # back, center of board
        "display.header":     (90, 40, False),   # back side, near MCU (moved up to avoid passive zone overlap)
    }
    for addr in headers:
        if addr in tht_positions:
            hx, hy, front = tht_positions[addr]
        else:
            # Fallback: spread evenly across board width
            idx = headers.index(addr)
            hx = margin + 20 + idx * (board_w - 2 * margin - 40) / max(len(headers) - 1, 1)
            hy = margin + header_zone_h / 2
            front = True
        place_collision_free(addr, hx, hy, front=front,
                             zone_bounds=(margin, margin, board_w - 2 * margin, header_zone_h))

    # USB-C — edge-mounted at right board edge for side-entry cable access.
    # Mid-mount connector: body on board, mouth flush with edge.
    # At 90° rotation, connector Y- (mouth, 6.5mm) maps to board X+.
    # Inset so mouth is ~1.5mm past edge (accessible for cable).
    usb_addr = "usb"
    if usb_addr in addr_map:
        fp = addr_map[usb_addr]
        usb_x = board_w - 5.0  # inset so mouth is flush with board edge
        usb_y = board_h / 2    # vertically centered
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(usb_x), pcbnew.FromMM(usb_y)))
        fp.SetOrientationDegrees(90)  # rotate so mouth faces right (toward rack side)
        w, h = tracker.get_footprint_dims(fp, pcbnew)
        is_through = tracker.is_tht(fp, pcbnew)
        tracker.register(usb_x, usb_y, w, h, "F", is_through, label=usb_addr)
        placed += 1
        # Remove from generic lists to prevent double placement
        if usb_addr in ics:
            ics.remove(usb_addr)
        if usb_addr in passives:
            passives.remove(usb_addr)

    # Place ICs below headers (back side) with collision detection
    ic_zone_h = passive_start_y - ic_start_y
    ic_start_x = margin + 5
    for i, addr in enumerate(ics):
        col = i % ic_cols
        row = i // ic_cols
        if row % 2 == 1:
            col = ic_cols - 1 - col
        x = ic_start_x + col * ic_spacing
        y = ic_start_y + row * ic_spacing
        place_collision_free(addr, x, y, front=False,
                             zone_bounds=(margin, ic_start_y - 2,
                                          board_w - 2 * margin, ic_zone_h + 2))

    # Place passives below ICs (back side) with collision detection
    passive_zone_h = board_h - passive_start_y - margin
    for i, addr in enumerate(passives):
        col = i % p_cols
        row = i // p_cols
        if row % 2 == 1:
            col = p_cols - 1 - col
        x = margin + 2 + col * passive_spacing
        y = passive_start_y + row * passive_spacing
        place_collision_free(addr, x, y, front=False,
                             zone_bounds=(margin, passive_start_y - 2,
                                          board_w - 2 * margin, passive_zone_h + 2))

    # Report overlaps
    overlaps = tracker.overlap_report()
    if overlaps:
        print(f"  WARNING: {len(overlaps)} remaining overlaps after collision-free placement:")
        for a, b, sa, sb, area in sorted(overlaps, key=lambda x: -x[4])[:10]:
            print(f"    {a} <-> {b} ({sa}/{sb}, {area:.1f}mm²)")
    else:
        print(f"  Overlap check: PASS (0 collisions among {placed} components)")

    print(f"  Board dimensions: {board_w:.1f} x {board_h:.1f} mm")
    print(f"  Placed {placed}/{len(addr_map)} components")

    board.Save(output_pcb)
    print(f"  Saved to {output_pcb}")


def place_components(input_pcb, output_pcb=None):
    """Place components using pcbnew API (control board — full panel layout).

    Requires KiCad's Python environment:
        DYLD_FRAMEWORK_PATH=...KiCad.app/Contents/Frameworks
        PYTHONPATH=...KiCad.app/.../site-packages
    """
    try:
        import pcbnew
    except ImportError:
        print("pcbnew not available. Run with KiCad's Python (see Makefile hw-place).")
        sys.exit(1)

    if output_pcb is None:
        output_pcb = input_pcb

    layout = load_layout()
    panel = layout["panel"]
    comp_map = load_component_map()
    pcb_dims = comp_map["pcb"]

    # PCB origin offset in faceplate coordinates
    # Faceplate coord (ox, oy) maps to PCB coord (0, 0)
    ox = pcb_dims["origin_x_mm"]
    oy = pcb_dims["origin_y_mm"]

    board = pcbnew.LoadBoard(input_pcb)

    # Enable 4 copper layers (F.Cu, In1.Cu, In2.Cu, B.Cu)
    # 2 layers is insufficient for 255 components / 319 nets at this density
    board.SetCopperLayerCount(4)

    # Set board outline (PCB is smaller than faceplate -- fits between rails)
    w_mm = pcb_dims["width_mm"]
    h_mm = pcb_dims["height_mm"]
    edge_layer = board.GetLayerID("Edge.Cuts")

    seg_coords = [
        (0, 0, w_mm, 0),
        (w_mm, 0, w_mm, h_mm),
        (w_mm, h_mm, 0, h_mm),
        (0, h_mm, 0, 0),
    ]
    for x1, y1, x2, y2 in seg_coords:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(edge_layer)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)

    # Build lookup from atopile_address to footprint
    addr_map = {}
    for fp in board.GetFootprints():
        if fp.HasFieldByName("atopile_address"):
            addr = fp.GetFieldText("atopile_address")
            addr_map[addr] = fp

    # Initialize collision tracker for the entire board
    tracker = CollisionTracker(w_mm, h_mm, clearance=0.5)

    placed = 0
    placed_addrs = set()
    warnings = []

    def place(addr, x_mm, y_mm, front=True, faceplate_coords=True, rotation_deg=0):
        """Place component and register with collision tracker.

        faceplate_coords=True means x/y are in faceplate space.
        """
        nonlocal placed
        if addr not in addr_map:
            warnings.append(addr)
            return
        fp = addr_map[addr]
        px = x_mm - ox if faceplate_coords else x_mm
        py = y_mm - oy if faceplate_coords else y_mm
        fp.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(px), pcbnew.FromMM(py)))
        if not front:
            if fp.GetLayer() == board.GetLayerID("F.Cu"):
                fp.Flip(fp.GetPosition(), False)
        if rotation_deg:
            fp.SetOrientationDegrees(rotation_deg)
        # Register actual bounding box with collision tracker
        bbox = fp.GetBoundingBox(False, False)
        bx1 = pcbnew.ToMM(bbox.GetLeft())
        by1 = pcbnew.ToMM(bbox.GetTop())
        bx2 = pcbnew.ToMM(bbox.GetRight())
        by2 = pcbnew.ToMM(bbox.GetBottom())
        is_through = tracker.is_tht(fp, pcbnew)
        side = "F" if front else "B"
        tracker.register_bbox(bx1, by1, bx2, by2, side, is_through, label=addr)
        tracker.register_label(fp, pcbnew, side)
        placed += 1
        placed_addrs.add(addr)

    # --- Through-hole components (front side, from panel layout) ---

    # Jacks -- all rotated. Both PJ398SM and PJ366ST have origin at panel hole.
    jack_rotation = layout["constants"].get("jack_rotation_deg", 0)

    # Jacks -- utility
    utility_addr_map = {
        "clk_in": "jacks.j_clk_in",
        "clk_out": "jacks.j_clk_out",
        "rst_in": "jacks.j_rst_in",
        "rst_out": "jacks.j_rst_out",
        "midi_in": "midi.jack_in",
        "midi_out": "midi.jack_out",
    }
    for jack in layout["jacks"]["utility"]:
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place(addr, jack["x_mm"], jack["y_mm"],
                  rotation_deg=jack_rotation)

    # Jacks -- clock/reset
    for jack in layout["jacks"].get("clock", []):
        addr = utility_addr_map.get(jack["id"])
        if addr:
            place(addr, jack["x_mm"], jack["y_mm"],
                  rotation_deg=jack_rotation)

    # Jacks -- output (gate1..4, pitch1..4, vel1..4, mod1..4)
    for jack in layout["jacks"]["output"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"],
              rotation_deg=jack_rotation)

    # Jacks -- CV input
    for jack in layout["jacks"]["cv_input"]:
        addr = f"jacks.j_{jack['id']}"
        place(addr, jack["x_mm"], jack["y_mm"],
              rotation_deg=jack_rotation)

    # Buttons -- track (t1..t4)
    for btn in layout["buttons"]["track"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- subtrack (gate, pitch, vel, mod)
    for btn in layout["buttons"]["subtrack"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Button -- pat (single item)
    pat = layout["buttons"].get("pat")
    if pat:
        place(f"buttons.btn_{pat['id']}", pat["x_mm"], pat["y_mm"])

    # Buttons -- feature (mute, route, drift, trns/xpose, var)
    feature_addr_map = {"trns": "xpose"}  # layout uses "trns", ato uses "xpose"
    for btn in layout["buttons"]["feature"]:
        ato_id = feature_addr_map.get(btn["id"], btn["id"])
        addr = f"buttons.btn_{ato_id}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- step (step1..step16)
    for btn in layout["buttons"]["step"]:
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- transport (play, reset, settings)
    for btn in layout["buttons"].get("transport", []):
        if btn["id"] == "settings":
            addr = "buttons.btn_settings"
        else:
            addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Buttons -- control strip (back, rand, clr)
    for btn in layout["buttons"].get("control_strip", []):
        addr = f"buttons.btn_{btn['id']}"
        place(addr, btn["x_mm"], btn["y_mm"])

    # Encoders
    for enc in layout["encoders"]:
        place(enc["id"], enc["x_mm"], enc["y_mm"])

    # SD card slot (front side, protrudes through faceplate cutout)
    # Try panel-layout first, fall back to component-map
    sd = layout.get("connectors", {}).get("sd_card", {})
    if "x_mm" not in sd or "y_mm" not in sd:
        sd = comp_map.get("connectors", {}).get("sd_card", {})
    if "x_mm" in sd and "y_mm" in sd:
        place("sd", sd["x_mm"], sd["y_mm"])

    # --- SMD components (back side) ---
    # Group unplaced SMD parts by their module prefix, then lay them out
    # in functional zones on the back of the board.
    # Convert faceplate coordinates to PCB coordinates for zone references
    jack_zone_x = layout["jacks"]["output"][0]["x_mm"] - ox
    step_x = layout["buttons"]["step"][0]["x_mm"] - ox
    center_x = w_mm / 2

    # --- Named component placement (back side) ---
    # All positions in PCB coords. Must avoid front-side THT pin areas.
    #
    # Front-side THT map (PCB coords):
    #   Track buttons:   x≈5.8,  y≈9..52
    #   Subtrack buttons: x≈100, y≈9..41
    #   Feature buttons:  x≈110, y≈9..52
    #   Transport buttons: x≈134, y≈10..34
    #   Step buttons:     x≈17..89, y≈88..98 (two rows)
    #   Encoders:         x≈11,y≈73  and  x≈105,y≈73
    #   Control strip:   x≈99..120, y≈93 (between step rows)
    #   Utility jacks:   x≈148..172, y≈10..45
    #   Output jacks:    x≈117..172, y≈48..99
    #   CV input jacks:  x≈117..172, y≈98..113

    lcd = layout.get("lcd_cutout", {})
    lcd_pcb_cx = lcd.get("center_x_mm", 54.78) - ox
    lcd_bottom_pcb = lcd.get("center_y_mm", 39.89) - oy + lcd.get("height_mm", 48.96) / 2

    # Board-to-board connector headers (THT, back side)
    # Two 2×16 shrouded headers (~11×43mm each) connecting control to main board.
    # Placed side by side in the LCD area (LCD is front-side only, back is available).
    place("connector.header_a", 25, 28, front=False, faceplate_coords=False)
    place("connector.header_b", 40, 28, front=False, faceplate_coords=False)

    # FPC connector for display — front side, below LCD cutout
    # Must be on front for ribbon cable access to display glass
    place("lcd_fpc", lcd_pcb_cx, lcd_bottom_pcb + 3, front=True, faceplate_coords=False)

    # MIDI optoisolator (IC, back side) — behind LCD, right of connector headers
    place("midi.opto", 80, 10, front=False, faceplate_coords=False)

    # MIDI input resistor — near the protection diode (CATHODE net) for routability
    place("midi.r_in", 25, 55, front=False, faceplate_coords=False)

    # --- Exclusion zones ---
    # The LCD display area is front-side only (display sits on front).
    # All placed components are already tracked by the CollisionTracker
    # (THT as "both" sides, SMD as their respective side).
    # Add the LCD zone as a static exclusion.
    lcd_pcb_cx = lcd.get("center_x_mm", 54.78) - ox
    lcd_pcb_cy = lcd.get("center_y_mm", 39.89) - oy
    lcd_hw = lcd.get("width_mm", 73.44) / 2
    lcd_hh = lcd.get("height_mm", 48.96) / 2
    tracker.register_zone(
        lcd_pcb_cx - lcd_hw - 2, lcd_pcb_cy - lcd_hh - 2,
        lcd_pcb_cx + lcd_hw + 2, lcd_pcb_cy + lcd_hh + 2,
        "F", label="LCD"
    )

    tht_count = sum(1 for a in placed_addrs
                    if a in addr_map and tracker.is_tht(addr_map[a], pcbnew))
    smd_count = len(placed_addrs) - tht_count
    print(f"  Collision tracker: 1 LCD(F) + {tht_count} THT(both) + "
          f"{smd_count} SMD(sided) = {tracker.count} entries")

    # --- Zone layout ---
    # Board: 177.88 x 106.5mm (PCB coords).
    # LCD cutout: ~14..92 x ~3..56 (with margin) -- upper left, ~44% of board
    # PGA2350:   ~91..119 x ~26..54 (with margin) -- upper center-right
    #
    # Available back-side area:
    #   Bottom strip: x=3..175, y=57..103 (full width, 172mm x 46mm)
    #   Right strip:  x=120..175, y=3..54  (55mm x 51mm)
    #
    # Zone layout (PCB coords, back side):
    #   +------+-----------+--------+-----+----------+
    #   |      |LCD CUTOUT | PGA    |midi | dac      |  0
    #   |      |(no-place) |        |     |          |
    #   |      |           |        |     |          |
    #   +------+-----------+--------+-----+----------+  57
    #   |display| buttons  |  mcu   |     jacks      |
    #   +------+-----------+--------+-----------------+  80
    #   |power | _top      |  leds  |                 |
    #   +------+-----------+--------+-----------------+ 104
    #   0      30          75      120               178

    # --- Dynamic zone placement ---
    # Instead of hardcoded zones, dynamically find the largest free areas
    # on the back side and fill them. The CollisionTracker already blocks
    # THT pin areas, so SMDs naturally flow into available gaps.

    # Group unplaced components by module prefix
    module_prefixes = ["leds.", "buttons.", "connector.", "display.", "midi.", "jacks."]
    zone_groups = {prefix: [] for prefix in module_prefixes}
    zone_groups["_top"] = []

    for addr in addr_map:
        if addr in placed_addrs:
            continue
        assigned = False
        for prefix in module_prefixes:
            if addr.startswith(prefix):
                zone_groups[prefix].append(addr)
                assigned = True
                break
        if not assigned:
            zone_groups["_top"].append(addr)

    # Build connectivity graph for netlist-aware placement
    all_smd_addrs = []
    for addrs in zone_groups.values():
        all_smd_addrs.extend(addrs)
    power_nets = identify_power_nets(board)
    conn_graph = build_connectivity_graph(board, all_smd_addrs, addr_map, power_nets)
    print(f"  Power nets filtered: {len(power_nets)}")
    print(f"  Connectivity edges: {sum(len(v) for v in conn_graph.values()) // 2}")

    ic_pin_threshold = 5
    ic_spacing = 10.0
    passive_spacing = 5.5

    # Per-module IC spacing overrides
    module_ic_spacing = {
        "leds.": 13.0,   # TLC LED drivers are large (~9×12mm body)
    }

    def classify_component(addr):
        fp = addr_map.get(addr)
        if not fp:
            return "passive"
        return "ic" if len(list(fp.Pads())) >= ic_pin_threshold else "passive"

    def compute_adaptive_spacing(rect_area, addrs, base_spacing):
        """Scale spacing based on how much free area is available vs component area.

        Returns (adapted_spacing, scale_factor) where scale_factor is 1.0 for
        tight fits and up to 2.5 for spacious areas.
        """
        total_comp_area = 0.0
        for addr in addrs:
            fp = addr_map.get(addr)
            if fp:
                needs_flip = fp.GetLayer() == board.GetLayerID("F.Cu")
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                fw, fh = tracker.get_footprint_dims(fp, pcbnew)
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                total_comp_area += fw * fh

        if total_comp_area == 0:
            return base_spacing, 1.0

        ratio = rect_area / total_comp_area

        if ratio < 1.5:
            scale = 1.0
        elif ratio > 2.0:
            scale = min(ratio / 2.0, 2.5)
        else:
            # Linear interpolation between 1.0 and 1.25 for ratio 1.5–2.0
            t = (ratio - 1.5) / 0.5
            scale = 1.0 + t * 0.25

        return base_spacing * scale, scale

    def place_in_rect(parts, zx, zy, zw, zh, spacing, label="", front=False,
                       label_aware=False):
        """Place parts in a grid within a rectangle, using collision-free search.

        When label_aware=True (ICs), the collision search uses an inflated
        bounding box that includes the reference designator text, so labels
        don't get clipped by neighboring components.
        """
        if not parts:
            return
        cols = max(1, int((zw - 1) / spacing) + 1)
        rows_needed = (len(parts) + cols - 1) // cols
        grid_w = (cols - 1) * spacing
        start_x = zx + (zw - grid_w) / 2
        start_y = zy + 1

        for i, addr in enumerate(parts):
            fp = addr_map.get(addr)
            if not fp:
                continue
            # Measure dims AFTER flipping to target side (matches what place() registers)
            needs_flip = (not front) and fp.GetLayer() == board.GetLayerID("F.Cu")
            if needs_flip:
                fp.Flip(fp.GetPosition(), False)
            fw, fh = tracker.get_footprint_dims(fp, pcbnew)
            is_through = tracker.is_tht(fp, pcbnew)

            # For ICs: inflate search envelope to include ref text
            if label_aware:
                ref_bbox = tracker.get_ref_text_bbox(fp, pcbnew)
                if ref_bbox:
                    body_bbox = fp.GetBoundingBox(False, False)
                    bx1 = pcbnew.ToMM(body_bbox.GetLeft())
                    by1 = pcbnew.ToMM(body_bbox.GetTop())
                    bx2 = pcbnew.ToMM(body_bbox.GetRight())
                    by2 = pcbnew.ToMM(body_bbox.GetBottom())
                    # Combined envelope of body + label
                    combined_w = max(bx2, ref_bbox[2]) - min(bx1, ref_bbox[0])
                    combined_h = max(by2, ref_bbox[3]) - min(by1, ref_bbox[1])
                    fw = max(fw, combined_w)
                    fh = max(fh, combined_h)

            if needs_flip:
                fp.Flip(fp.GetPosition(), False)  # flip back — place() will flip again

            col = i % cols
            row = i // cols
            if row % 2 == 1:
                col = cols - 1 - col
            desired_x = start_x + col * spacing
            desired_y = start_y + row * spacing

            x, y = tracker.find_free(
                desired_x, desired_y, fw, fh,
                side="B", is_tht=is_through,
                zone_bounds=(zx, zy, zw, zh),
                step=0.5,
            )
            place(addr, x, y, front=False, faceplate_coords=False)

    def place_module_dynamic(addrs, label):
        """Place a module's components into the largest free area, then rescan."""
        if not addrs:
            return

        ics = size_sort(
            [a for a in addrs if classify_component(a) == "ic"], addr_map, pcbnew)
        passives = size_sort(
            [a for a in addrs if classify_component(a) == "passive"], addr_map, pcbnew)

        # Separate THT components from SMD — THT need both-sides-free placement
        tht_ics = [a for a in ics if tracker.is_tht(addr_map[a], pcbnew)]
        smd_ics = [a for a in ics if not tracker.is_tht(addr_map[a], pcbnew)]
        tht_passives = [a for a in passives if tracker.is_tht(addr_map[a], pcbnew)]
        smd_passives = [a for a in passives if not tracker.is_tht(addr_map[a], pcbnew)]

        # Place THT components first — they need space clear on BOTH sides.
        # Place each THT component individually near its connected peers.
        #
        # Key fix: find_free assumes (cx, cy) is the bbox CENTER, but footprint
        # reference points may be offset (e.g. SIP-9 ref at pin 1 = top).
        # We compute the bbox center offset and adjust search accordingly.
        if tht_ics or tht_passives:
            for addr in tht_ics + tht_passives:
                fp = addr_map.get(addr)
                if not fp:
                    continue
                needs_flip = fp.GetLayer() == board.GetLayerID("F.Cu")
                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)
                fw, fh = tracker.get_footprint_dims(fp, pcbnew)

                # Compute bbox center offset from footprint reference point
                orig_pos = fp.GetPosition()
                fp.SetPosition(pcbnew.VECTOR2I(0, 0))
                bbox = fp.GetBoundingBox(False, False)
                off_x = (pcbnew.ToMM(bbox.GetLeft()) + pcbnew.ToMM(bbox.GetRight())) / 2
                off_y = (pcbnew.ToMM(bbox.GetTop()) + pcbnew.ToMM(bbox.GetBottom())) / 2
                fp.SetPosition(orig_pos)

                if needs_flip:
                    fp.Flip(fp.GetPosition(), False)

                # Target: near connected components (average position)
                neighbors = conn_graph.get(addr, [])
                if neighbors:
                    positions = []
                    for n in neighbors:
                        nfp = addr_map.get(n)
                        if nfp:
                            npos = nfp.GetPosition()
                            positions.append((pcbnew.ToMM(npos.x) - ox,
                                              pcbnew.ToMM(npos.y) - oy))
                    if positions:
                        target_x = sum(p[0] for p in positions) / len(positions)
                        target_y = sum(p[1] for p in positions) / len(positions)
                    else:
                        target_x, target_y = w_mm / 2, h_mm / 2
                else:
                    target_x, target_y = w_mm / 2, h_mm / 2

                # Search at bbox-center position (not ref point)
                search_cx = target_x + off_x
                search_cy = target_y + off_y

                found_cx, found_cy = tracker.find_free(
                    search_cx, search_cy, fw, fh,
                    side="B", is_tht=True, step=0.5)

                # Convert found bbox center back to ref point for placement
                place_x = found_cx - off_x
                place_y = found_cy - off_y

                place(addr, place_x, place_y, front=False, faceplate_coords=False)

        # Place SMD components — only need back-side free space
        ic_sp_used, ic_scale = None, 1.0
        pass_sp_used, pass_scale = None, 1.0
        ic_rect_area, pass_rect_area = 0.0, 0.0

        if smd_ics or smd_passives:
            free_rects = tracker.find_largest_free_rects("B", resolution=1.0, count=5)
            if not free_rects:
                print(f"    {label}: WARNING no free area found!")
            else:
                if smd_ics:
                    rect = free_rects[0]
                    zx, zy, zw, zh = rect
                    ic_rect_area = zw * zh
                    base_sp = module_ic_spacing.get(label, ic_spacing)
                    ic_sp_used, ic_scale = compute_adaptive_spacing(
                        ic_rect_area, smd_ics, base_sp)
                    place_in_rect(smd_ics, zx, zy, zw, zh, ic_sp_used, label,
                                  label_aware=True)
                    free_rects = tracker.find_largest_free_rects("B", resolution=1.0, count=5)
                if smd_passives and free_rects:
                    rect = free_rects[0]
                    zx, zy, zw, zh = rect
                    pass_rect_area = zw * zh
                    pass_sp_used, pass_scale = compute_adaptive_spacing(
                        pass_rect_area, smd_passives, passive_spacing)
                    place_in_rect(smd_passives, zx, zy, zw, zh, pass_sp_used, label,
                                  label_aware=False)

        n_ics = len(ics)
        n_pass = len(passives)
        n_tht = len(tht_ics) + len(tht_passives)
        tht_note = f" ({n_tht} THT)" if n_tht else ""

        ic_sp_str = f"{ic_sp_used:.1f}mm" if ic_sp_used else f"{module_ic_spacing.get(label, ic_spacing):.0f}mm"
        if ic_scale > 1.01:
            ic_sp_str += f" (adaptive {ic_scale:.1f}×)"
        pass_sp_str = f"{pass_sp_used:.1f}mm" if pass_sp_used else f"{passive_spacing:.0f}mm"
        if pass_scale > 1.01:
            pass_sp_str += f" (adaptive {pass_scale:.1f}×)"

        utilization = ""
        if ic_rect_area > 0:
            total_comp = sum(
                tracker.get_footprint_dims(addr_map[a], pcbnew)[0]
                * tracker.get_footprint_dims(addr_map[a], pcbnew)[1]
                for a in smd_ics if addr_map.get(a))
            pct = (total_comp / ic_rect_area * 100) if ic_rect_area else 0
            utilization = f" | {pct:.0f}% of {ic_rect_area:.0f}mm²"

        print(f"    {label:12s}: {n_ics:2d} ICs ({ic_sp_str}) + {n_pass:2d} passives "
              f"({pass_sp_str}){tht_note}{utilization}")

    # Place each module group, largest modules first (they need the most space)
    module_order = sorted(zone_groups.keys(),
                          key=lambda k: len(zone_groups[k]), reverse=True)
    for prefix in module_order:
        addrs = zone_groups[prefix]
        if addrs:
            place_module_dynamic(addrs, prefix)

    # Print summary
    print(f"  Placed {placed}/{len(addr_map)} components")
    if warnings:
        print(f"  {len(warnings)} addresses not found:")
        for w in warnings:
            print(f"    - {w}")

    # Estimate total wire length (Manhattan distance of non-power net connections)
    net_pads = defaultdict(list)
    for fp in board.GetFootprints():
        pos = fp.GetPosition()
        px, py = pcbnew.ToMM(pos.x), pcbnew.ToMM(pos.y)
        for pad in fp.Pads():
            net_name = pad.GetNetname()
            if net_name and net_name not in power_nets:
                net_pads[net_name].append((px, py))
    total_wire = 0.0
    for net_name, pads in net_pads.items():
        if len(pads) < 2:
            continue
        cx = sum(p[0] for p in pads) / len(pads)
        cy = sum(p[1] for p in pads) / len(pads)
        for px, py in pads:
            total_wire += abs(px - cx) + abs(py - cy)
    print(f"  Estimated wire length (non-power): {total_wire:.0f} mm")

    # --- Validate placement using CollisionTracker ---
    # The tracker already has all components registered from place() calls.
    # Now do a final independent verification scan directly from KiCad footprints.

    def fp_label(fp):
        if fp.HasFieldByName("atopile_address"):
            return fp.GetFieldText("atopile_address")
        return fp.GetReference()

    footprints = list(board.GetFootprints())

    # 1. Out-of-bounds check
    oob_margin = 1.0
    oob = []
    for fp in footprints:
        bbox = fp.GetBoundingBox(False, False)
        x1 = pcbnew.ToMM(bbox.GetLeft())
        y1 = pcbnew.ToMM(bbox.GetTop())
        x2 = pcbnew.ToMM(bbox.GetRight())
        y2 = pcbnew.ToMM(bbox.GetBottom())
        if x1 < -oob_margin or y1 < -oob_margin or x2 > w_mm + oob_margin or y2 > h_mm + oob_margin:
            oob.append((fp_label(fp), x1, y1, x2, y2))
    if oob:
        print(f"  WARNING: {len(oob)} components extend outside board ({w_mm}x{h_mm}mm):")
        for label, x1, y1, x2, y2 in oob[:20]:
            print(f"    - {label} bbox ({x1:.1f},{y1:.1f})-({x2:.1f},{y2:.1f})")
    else:
        print(f"  Bounds check: PASS ({len(footprints)} footprints within board)")

    # 2. Overlap check — independent scan (not relying on tracker data)
    # This catches any overlaps the tracker might have missed or allowed.
    min_overlap_mm2 = 0.5
    fp_data = []
    for fp in footprints:
        bbox = fp.GetBoundingBox(False, False)
        fp_data.append((
            fp_label(fp),
            (pcbnew.ToMM(bbox.GetLeft()), pcbnew.ToMM(bbox.GetTop()),
             pcbnew.ToMM(bbox.GetRight()), pcbnew.ToMM(bbox.GetBottom())),
            "F" if fp.GetLayer() == board.GetLayerID("F.Cu") else "B",
            tracker.is_tht(fp, pcbnew),
        ))

    overlaps = []
    for i in range(len(fp_data)):
        label_a, bbox_a, side_a, tht_a = fp_data[i]
        for j in range(i + 1, len(fp_data)):
            label_b, bbox_b, side_b, tht_b = fp_data[j]
            # Same side: always check. Cross side: only if one is THT.
            if side_a == side_b:
                kind = f"same-side ({side_a})"
            elif tht_a or tht_b:
                kind = "THT cross-side"
            else:
                continue
            dx = min(bbox_a[2], bbox_b[2]) - max(bbox_a[0], bbox_b[0])
            dy = min(bbox_a[3], bbox_b[3]) - max(bbox_a[1], bbox_b[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= min_overlap_mm2:
                    overlaps.append((label_a, label_b, kind, area))

    if overlaps:
        overlaps.sort(key=lambda x: -x[3])
        print(f"  WARNING: {len(overlaps)} footprint overlaps detected:")
        for label_a, label_b, kind, area in overlaps[:30]:
            print(f"    - {label_a} <-> {label_b} ({kind}, {area:.1f}mm²)")
        if len(overlaps) > 30:
            print(f"    ... and {len(overlaps) - 30} more")
    else:
        print(f"  Overlap check: PASS (0 collisions among {len(fp_data)} footprints)")

    # 3. Label overlap check — informational warnings
    label_data = []
    for fp in footprints:
        ref_bbox = tracker.get_ref_text_bbox(fp, pcbnew)
        if ref_bbox:
            side = "F" if fp.GetLayer() == board.GetLayerID("F.Cu") else "B"
            label_data.append((fp.GetReference(), ref_bbox, side))

    label_overlaps = []
    # Label vs body overlaps (same side)
    for ref_name, lbox, lside in label_data:
        for fp_name, fbox, fside, tht in fp_data:
            if lside != fside and not tht:
                continue
            # Skip self (ref belongs to this footprint)
            if ref_name in fp_name:
                continue
            dx = min(lbox[2], fbox[2]) - max(lbox[0], fbox[0])
            dy = min(lbox[3], fbox[3]) - max(lbox[1], fbox[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= 0.3:
                    label_overlaps.append((
                        f"label:{ref_name}", fp_name, "label-body", area))

    # Label vs label overlaps (same side)
    for i in range(len(label_data)):
        ref_a, lbox_a, side_a = label_data[i]
        for j in range(i + 1, len(label_data)):
            ref_b, lbox_b, side_b = label_data[j]
            if side_a != side_b:
                continue
            dx = min(lbox_a[2], lbox_b[2]) - max(lbox_a[0], lbox_b[0])
            dy = min(lbox_a[3], lbox_b[3]) - max(lbox_a[1], lbox_b[1])
            if dx > 0 and dy > 0:
                area = dx * dy
                if area >= 0.3:
                    label_overlaps.append((
                        f"label:{ref_a}", f"label:{ref_b}", "label-label", area))

    if label_overlaps:
        label_overlaps.sort(key=lambda x: -x[3])
        print(f"  Label overlaps: {len(label_overlaps)} (informational)")
        for la, lb, kind, area in label_overlaps[:15]:
            print(f"    - {la} <-> {lb} ({kind}, {area:.1f}mm²)")
        if len(label_overlaps) > 15:
            print(f"    ... and {len(label_overlaps) - 15} more")
    else:
        print(f"  Label overlaps: 0 (clean)")

    board.Save(output_pcb)
    print(f"  Saved to {output_pcb}")


def detect_board_type(input_pcb):
    """Detect board type from PCB filename. Returns 'main' or 'control'."""
    basename = os.path.basename(input_pcb).lower()
    if "main" in basename:
        return "main"
    return "control"


def main():
    parser = argparse.ArgumentParser(
        description="Place components on KiCad PCB."
    )
    parser.add_argument(
        "--board",
        choices=["control", "main"],
        default=None,
        help="Board type: 'control' (panel layout) or 'main' (compact grid). "
             "Auto-detected from filename if not specified.",
    )
    parser.add_argument("input_pcb", help="Input .kicad_pcb file")
    parser.add_argument("output_pcb", nargs="?", default=None, help="Output .kicad_pcb file")
    args = parser.parse_args()

    board_type = args.board or detect_board_type(args.input_pcb)
    print(f"  Board type: {board_type}")

    if board_type == "main":
        place_main_board(args.input_pcb, args.output_pcb)
    else:
        place_components(args.input_pcb, args.output_pcb)


if __name__ == "__main__":
    main()
